=== Creating and Updating Styles

There are two issues regarding the HTTP PUT method and how it might be applied to OGC API - Styles. The first issue is related to the fact that there can be different stylesheets for a single style. An API can offer a resource in multiple encodings, for example SLD, ArcGIS, MapInfo, Mapbox or others. This leads to the questions of: Should changes to a resource be propagated to each of the encodings? What happens in situations where the encodings do not support a concept that is supported by other encodings? A https://github.com/opengeospatial/ogcapi-styles/pull/42[pull request] was created that addresses aspects of this challenge. The pull request will be discussed by the SWG after the code sprint.

The second issue is regarding specification of the PUT mechanism in the OGC API - Styles  candidate Standard itself. _OGC API - Features - Part 4_ was the first of the OGC API candidate Standards to specify interfaces for create, replace, update, and delete operations. _OGC API - Features - Part 4_ has two different requirements classes, one is general and is written for any resource. The other requirements class is for features. _OGC API - Styles_ implements the general resource requirements class - which could be eventually moved to _OGC API - Common_. The idea is for the general resource requirements class to support the ability to create a style when it receives a PUT request with an identifier.
