=== HTML Previews

There was a discussion about the retrieval of HTML previews of data from an OGC API implementation. This followed the work described in <<pygeoapi_leaflet_coverages>> regarding a coverage viewer for pygeoapi. It was noted that the ability to request an HTML representation of a dataset means that an OGC API could potentially also offer support for querying a dataset through a web browser. This leaves the question of how a query language such as CQL2 could be applied to tile matrix sets. Further, the HTML Preview capability creates an opportunity to enable the actual data to be queried such that the value of a location on a coverage can be retrieved rather than the RGB (Red-Green-Blue) values of the image that is presented. The sprint participants noted that this could be a topic for a testbed or another type of innovation initiative.

Another topic discussed in relation to HTML Previews was that the `Accept` header or "f" parameter indicated the format of the response payload, but not the format of any embedded elements. So there is an expectation that the web browser supports whichever image format is embedded in the HTML response of the API. One option is to introduce a recommendation that if one of the media types is `text/html`, and the other is an image, then the server should return an HTML Preview that contains an image in the format specified. The sprint participants also noted that HTML offers a `<picture>` element which contains an `<img>` element, as well as zero or more `<source>` elements that offer alternative versions of an image for different situations <<WHATWG_HTML>>. A web browser considers each `<source>` element and selects the most appropriate among them. If there are no appropriate options, the web browser uses the URL in the `src` attribute of the `<img>` element.
