=== JPEG or PNG responses

JPEG images are typically an order of magnitude smaller in byte size than PNG images of a similar width and height in pixels. JPEG images therefore result in a much more responsive experience, but they do not support transparency, so layer overlays are impossible. PNG images, on the other hand, do support transparency, but are typically larger in byte size for a similar width and height in pixels. Some client implementations deal with this by requesting the bottom layer as JPEG and all overlay layers as PNG, but this is far from ideal. One somewhat common solution is to support a "JPEG or PNG" format (represented by a requested content type of "image/x-jpegorpng" or "image/jpgpng" or a format string of "jop"). When this format is requested, the server can return the requested image in the optimal image format (typically PNG if there's transparency and JPEG otherwise). Several implementations, including CubeSERV, have taken this approach, and it has proven to be a highly effective optimization. However, the WMS and WMTS specifications failed to standardize such a request format, so this optimization is not interoperable.

This is not an issue for the "OGC API - Maps" candidate Standard and the "OGC API - Tiles" Standard, since they support format (i.e., content type) negotiation through use of the HTTP `Accept` request header. A client can simply indicate `Accept: image/png, image/jpeg`, which literally means "give me whichever of these two formats you consider the most appropriate". And as a bonus, a typical web browser will send an `Accept` string which gives image/jpeg and image/png equal weighting, so JPEG-or-PNG negotiation can automatically occur even through simple web-browser requests. It should be noted that some modern web browsers send an  `Accept: image/avif, image/webp, */*`` header, which suggests that they prefer some of the newer formats which also happen to support an alpha channel. Therefore, use of the `Accept` header as already implemented by OGC API Standards also enables support for other encoding options.

However, there is a concern that many implementers of OGC API - Maps and OGC API - Tiles might not recognize the importance of this logic, and would likely write code which just chooses the first supported format in the list. There is therefore a need for awareness of this mechanism because such a mechanism is important enough to be explicitly provided as a recommendation in both https://docs.ogc.org/DRAFTS/20-058.html[OGC API - Maps - Part 1: Core] and https://docs.ogc.org/is/20-057/20-057.html[OGC API - Tiles - Part 1: Core].

A Recommendation could be added to an OGC API - Maps User Guide or some other developer resource. The sprint participants suggested that the SWG considers the following text for addition to a User Guide:

* If both "image/png" and "image/jpeg" are supported at an endpoint and are present in the HTTP "Accept" request header with the same q value, and no other supported output format is present with a higher q value, the server should return the requested image in whichever of these two formats is considered optimal (typically PNG if there's transparency and JPEG otherwise).

Regarding the "f" parameter, if servers implement an "f" parameter that overrides the HTTP "Accept" request header, the servers would have the option of supporting custom values such as "jop" or "image/x-jpegorpng" which would trigger the optimization. However, since "jop" or "image/x-jpegorpng" are not standardized parameter values for indicating an encoding, the Standards need not provide any recommendations to this effect.
