=== Security/access control

The EuroGeographics WMS access token as applied in OGC API - Maps via pygeoapi brought forth questions about how cascading / broker services deal with secure services. The pygeoapi documentation provides an overview on https://dive.pygeoapi.io/advanced/security-access-control/[security and access control]. The September 2020 OGC API Code Sprint included a security thread (<<ogc20-091>>), however since then there has not been a similar thread in OGC Code Sprints. There was a suggestion to have a sprint (or thread in same) focused on general security/access control issues, across OGC API and broader OGC Standards. There are several implementations of OGC API Standards that implement access control mechanisms. Such a code sprint could pull in lessons learnt from many of the OGC API implementations that support access control, for example Ordnance Survey's https://osdatahub.os.uk/docs/ofa/gettingStarted[NGD API - Features], NLS Finland's https://www.maanmittauslaitos.fi/en/maastotietokannan-kyselypalvelu/tekninen-kuvaus[Topographic Database], and those from the https://docs.ogc.org/per/21-020r1.html[OGC Testbeds] (<<ogc21-020r1>>).
