==== Secure and Asynchronous Catalogue

There are many factors that influence the response time of a server when it receives a request from a client application. Socket timeouts can occur while the client application waits for a response from the server.
To avoid losing the response for requests that require a processing time that is longer than socket timeout, the communication to the client application may continue 'asynchronously'. That means that the service to client application communication does not take part on the original sockets; it happens somehow else.

The proposed solution from the OGC Testbed-18 Secure & Asynchronous Catalogue team was to leverage the HTTP _Prefer_ header (as defined in IETF https://www.rfc-editor.org/rfc/rfc7240[RFC 7240]) that enables the client application to indicates to the server about the response preferences. For example, a _Prefer_ header with the value “_respond-async, wait=10_” indicates that the client application is able (willing) to wait 10 seconds for a response and that an asynchronous response is preferred. To control a generic carry-on for OGC APIs via asynchronous follow-up communication, the Testbed 18 team recommended definition of OGC specific _Prefer_ header parameters. One example is to define the parameter _subscription_ which links to an existing subscription that defines a particular way of carrying-on. For example, the following Prefer header extends the previous example indicating the service to use a particular subscription identified via the URI: “_Prefer: respond-async, wait=10, subscription=https://ogc.demo.secure-dimensions.de/sms/subscriptions/4711_”. In case the service honors the indicated client application preference, the HTTP response must contain the HTTP Header Preference-Applied including the parameter that was accepted. For the previous example, the acceptance of the subscription option is expressed with the HTTP Response header “_Preference-Accepted: subscription_”.

This proposed solution requires however that a generic Subscription Management Service (SMS) exists and that the OGC API implementation introspects the HTTP Request headers and checks for the _Prefer_ header. This checking can be achieved in a generic OGC API gateway for example. For the Code Sprint, the Testbed-18 team sought to extend the SMS prototype implemented during Testbed-18 with an additional “carry-on” communication: WebPush as defined by https://www.w3.org/TR/push-api/[W3C Push API]. This required a client and a service implementation. The code sprint provided an opportunity for the Testbed-18 team to explore the proposed solution in collaboration with other sprint participants.
