==== ISO 19157-3

To facilitate dataset comparisons, evaluations and data quality reports (metadata or a quality evaluation report) have to be expressed in a comparable way, and it is necessary to have a common understanding of the data quality measures that have been used. An example of such common understanding of a standard quality measure is defined in ISO 19157-1:2023 Geographic information - Data quality - Part 1: General requirements. This standard defines the structure of a data quality measure as well as all additional attributes describing a data quality measure - see in .... [insert Figure from here: https://github.com/i2vana/ISO19157-3/blob/main/OGC-CodeSprint/img/ISO19157-1_dataQualityMeasure.PNG]

// Please revise as per your cross-ref style

[#img-dqm]
// image caption should be this: Structure of a data quality measure as defined in ISO 19157-1:2023
// the image to be insterted is here: https://github.com/i2vana/ISO19157-3/blob/main/OGC-CodeSprint/img/ISO19157-1_dataQualityMeasure.PNG


To comply with current best practice for sharing data over the web, these measures have to reside in a machine-actionable data quality measures register. Such register is currently under development at ISO/TC211 and OGC. ISO 19157-3 Geographic information - Data quality - Part 3: Data quality measures register will be the standard defining the components and content structure of a register for data quality measures, and the registration and maintenance procedure. All of this is compliance with ISO 19135 Geographic information - Registration and registration procedures, a governing standard for all ISO/TC211 registers. The measures will be hosted in the ISO 19157-3 register will be hosted at OGC, the Registration Authority of ISO 19157-3. Current version implemented at OGC RAINBOW contains first set of 80+ recognized standard data quality measures (e.g. such as the Root Mean Square Error used for evaluation positional accuracy, or the Misclassification Matrix used to evaluate the attribute accuracy) and these were used in first few tests as part of the Code Sprint. Full version of the ISO 19157-3 Data Quality measures register is expected to be published together with the ISO 19157-3 standard in early 2026.
