==== OGC API - Environmental Data Retrieval

The https://ogcapi.ogc.org/edr[OGC API - Environmental Data Retrieval (EDR)] Standard provides a family of lightweight interfaces to access Environmental Data resources. Each resource addressed by an EDR API maps to a defined query pattern. This Standard identifies resources, captures compliance classes, and specifies requirements which are applicable to OGC Environmental Data Retrieval API’s. This Standard addresses both discovery and query operations. Discovery operations enable the API to be interrogated to determine its capabilities and retrieve metadata about the published resource. Query operations allow Environmental Data resources to be retrieved from the underlying data store based upon simple selection criteria, defined by this standard and selected by the client.

Version 1.1 of OGC API - EDR has been published (<<OGC19-086r6>>). The EDR API Standards Working Group (SWG) has recently obtained approval to publish Part 2 of the Standard: "OGC API - Environmental Data Retrieval - Part 2: Publish-Subscribe workflow" (<<bib_ogcapiedrpart2>>). The focus of the EDR API-related work in this code sprint is therefore on the use of Part 2 of the Standard. Work continues on defining improvements to Part 1: Core Version 1.1 to be known as Version 1.2.
