==== OGC SensorThings API

The https://ogcapi.ogc.org/sensorthings/[OGC SensorThings API] Standard provides an open and harmonized way to interconnect devices, applications, and data over the web and on the Internet of Things (IoT) (<<OGC18-088>>). At a high level the SensorThings API provides two main parts, namely Part I - Sensing, and Part II - Tasking. The Sensing part of the Standard provides a way to manage and retrieve observations and metadata from different sensor systems. The Tasking part of the Standard provides a way for tasking IoT devices, such as actuators and sensors. The SensorThings API follows REST principles and uses JSON for encoding messages as well as Message Queuing Telemetry Transport (MQTT) for publish/subscribe operations.

In this code sprint, activity related to the OGC SensorThings API focused on a WebSub extension to the OGC SensorThings API Standard. The OGC SensorThings API Extension `WebSub` prototype is based on the https://www.w3.org/TR/websub/[W3C WebSub Recommendation]. The prototype supports subscribe/unsubscribe and opaque discovery capabilities that are offered by implementations of OGC SensorThings API.
