==== OGC TEAM Engine

The https://opengeospatial.github.io/teamengine/[Test, Evaluation, And Measurement (TEAM) Engine] is a testing facility that executes test suites implemented using the TestNG framework or the OGC Compliance Test Language (CTL). It is typically used to verify specification compliance and is the official test harness of the https://www.ogc.org/compliance[OGC Compliance & Interoperability Testing & Evaluation (CITE)] program. TEAM Engine is able to import Executable Test Suite (ETS) libraries that are implemented using the TestNG and CTL. Each ETS is implemented to execute source code that reflects the test methods specified in the Abstract Test Suite (ATS) that is specified in an associated OGC Standard. For the this code sprint, the TEAM Engine activity focused on implementing an initial 'alpha' version of the link:https://www.ogc.org/requests/ogc-requests-public-comment-on-json-and-xml-encodings-for-training-data-markup-language-for-artificial-intelligence-standard/[OGC Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Part 2: JSON Encoding] candidate Standard.