=== GeoXAML 3.0

This code sprint activity demonstrated the basics for enabling powerful Attribute Based Access Control including geospatial conditions. Regarding a production solution, the request rewriting to inject (not only) geospatial conditions via the OGC Filter parameter can be considered high-performance: little information is required to create a request in the PEP and send it to the GeoPDP. Likewise, the response from the GeoPDP to the PEP includes a decision and zero to multiple obligations that control the construction of the Filter. The deployment of the PDP is missing critical, but because this backend service is
stateless, scaling is “straight forward” in cloud infrastructures.

A successful demonstration was given during the last day brief back. The QGIS application was used to connect to the GeoServer WFS using the regular OGC WFS 2.0 service. Invisible to the client, the PEP modified the WFS request sent by QGIS based on the access rights expressed in the GeoXACML policy.