=== ISO 19115 activity by OpenWork

==== Background

OpenWork participated in the code sprint, supported by both the OGC and the Australia and New Zealand Intergovernmental Committee on Survey and Mapping (ICSM). Byron Cochrane, a metadata expert from OpenWork, participated on behalf of OpenWork with the primary role in the code sprint of sharing technical expertise on ISO 19115 metadata. This expertise included participation in standard development, implementation, development of tools and guidance. A significant part of this expertise has been gained through involvement in the ICSM Metadata Working Group (MDWG) and chairing of the OGC Metadata and Catalogue Domain Working Group, as well as participation in the OGC API - Records Standards Working Group.

One of the challenges of assisting and advising organizations in creating, managing and using spatial metadata is that due to the apparent proliferation of solutions, it has become more challenging to advise on which metadata solutions are best suited to a particular organization's needs. This is partly because the role of metadata and catalogues is multifaceted and varied across domains. Currently, unfortunately, some of the communities providing the tools or solutions do not offer such guidance. A framework by which such guidance could be created and shared was a primary goal of OpenWork's participation.

Other sprint goals included to:

*	Examine the possibility of creating a JSON encoding of ISO 19115-1
*	Create Crosswalks between ISO 19115-1, STAC and OGC API Records

==== Day 1

The focus of Day One of the code sprint was for participants to better understand the primary components: OGC API - Records, STAC, ISO 19115, and JSON-FG, as well as their histories, capabilities, use and future development plans. OpenWork led an hour-long presentation and discussion on ISO 19115 and related standards.

===== Presentation of ISO 19115

OpenWork briefed the sprint participants, highlighting issues around the lack of understanding of the differences between the standard names and versions of ISO 19115. In Australia and New Zealand, ICSM strongly endorsed the ISO 19115-1 metadata standard and deprecated the previous ISO 19115 profiles. This support includes the latest version, ISO 19115-1:2014/Amd2:2020, which provides improved support for capturing information related to coordinate drift due to tectonic movement - a significant issue in Australia where coordinate values can change over one and a half meters in 20 years. However, it is clear that many professionals confuse the versions and do not understand why changes exist. For example, a common confusion is referencing ISO 19115:2003 as ISO 19115-1 (initially likely to contrast with ISO 19115-2:2009 Extensions for imagery and gridded data). Yet ISO 19115-1 was not released until 2014. As a result, today, many software vendors claim support for ISO 19115-1 when they only support the older ISO 19115:2003 standard. Byron Cochrane explained that, for Europe, this issue is aggravated by the fact that the INSPIRE framework of the European Union (EU) has yet to provide a mechanism to support ISO 19115-1 even though work on this standard was well underway when the EU launched INSPIRE. The INSPIRE community must address this situation as it prohibits many in Europe from using the improved standards and limits software developers' willingness to include support for enhanced standards worldwide.

Two significant discussions resulted from this presentation. The first involved the value of namespaces in encoded metadata. The namespace issue is closely related to the desire to create a canonical JSON encoding of ISO 19115-1. One position was that many JSON developers dislike using namespaces and tend to remove them if they are present. A contrasting view posited that namespaces are an elegant approach for reducing ambiguity in data and, when not used, are often eventually replaced by less friendly solutions. A question raised and unanswered was whether a canonical encoding of ISO 19115-1 would be possible.

This first discussion led to the second. The question was, "What would the best approach to a JSON encoding of ISO 19115-1 be?" Would it be best to create a fully compliant canonical version like ISO 19115-3 encoded in JSON? Or would it be better to take a more piecemeal approach and extend OGC API - Records where needed until it could provide a fully compliant record? The challenges of directly aligning the GeoJSON format used by OGC API - Records with ISO 19115-1 and the desire to improve crosswalks for at least some elements during the code sprint led OpenWork to take the latter approach. This proved to be the right approach for this sprint's shorter-term purposes and outcomes.

===== Crosswalks

For the remainder of Day 1, taking the advice and support of participants from MariaDB CubeWerx and the Meteorological Service of Canada (MSC), OpenWork undertook an effort to improve the ability to create crosswalks for keywords in ISO 19115-1 to OGC API — Records. OGC API — Records offers two possible locations for Keywords — Keywords and Themes/Concepts. Themes/Concepts were chosen as the natural fit. OGC API — Records follows the pattern of DCAT in this. The “Keywords” class is to hold free text tags. The Theme/Concepts can also contain free text but primarily support keyword concepts sourced from controlled vocabularies. (This could potentially confuse developers, thus one of the classes might need to be considered for removal.)

By the end of the evening, OpenWork had altered the YAML schema to support the ingestion of ISO 19115-1 keyword elements with controlled vocabularies. OpenWork also proposed changing the names of the relevant classes for clarity suggesting "keywords" be "tags" and "themes" be "keywords". In addition, to provide a method to retrieve the original entire ISO 19115-1 record, OpenWork proposed a new element, "source", to link a complete ISO 19115-3 record, should it exist. This latter recommendation was rejected in favor of guidance on using the existing “link” class to provide this functionality.

==== Day 2

On Day 2, OpenWork focused on creating a Record document conforming to the OGC API - Records candidate standard to test the guidance that OpenWork had developed the previous evening. Several changes ensued, mainly relating to the ability to provide resolvable URIs to both the concepts and their controlled vocabularies. There is a need for more work and testing.

Discussions clarified the roles that traditional catalogues, OGC API - Records and STAC serve. These can be summarized as follows:

*	STAC is most appropriate for fine-level metadata - particularly cataloguing scenes in a collection of images to allow their discovery
*	Part 1 (the Core part) of OGC API — Records focuses on the general discovery of spatial resources of any type. Because of this, it may not be useful or appropriate to capture in the Core part of OGC API — Records any ISO 19115-1 metadata that exists for purposes other than discovery. However, future extensions of OGC API — Records may support purposes other than discovery.
*	ISO 19115-1 exists to document and manage a resource fully. Provenance, structural, informative, administrative and other metadata elements exist in this standard catalogue. This resource is most useful after discovery.

==== Day 3

The focus of OpenWork on Day 3 was to start providing a framework to guide the use of OGC API - Records. This followed the early discussion regarding how much structure should be encoded in the standard. Creating a rigid standard was not seen as desirable. However, a guidance document that could provide authoritative direction would be acceptable. The immediate aim was to support crosswalks from ISO 19115 through this approach.

On Day 3, OpenWork focused on the keyword (themes) class for which Byron Cochrane had created crosswalks earlier in the sprint. Inclusion of additional classes and crosswalked elements could be added over time. A pattern language approach, applied in OpenWork's work with ICSM, was used as a template. Such documentation, while useful, requires a great deal of effort to produce. But it allows the schema to remain simple. However, automated validation is difficult to provide through this approach.
