[[gimi]]

==== NGIIS GIMI

Next Generation ISR Imagery Standards (NGIIS) is a program of work to modernise ISR still and motion imagery standards. Key priorities are:

 - Leverage open commercial media standards to integrate still and motion imagery into a single container
 - Harmonization of still and motion imagery metadata through development of an imagery domain ontology
 - Address a broad range of use cases with a common, integrated suite of capabilities
 - Enable automation
 - Support to disadvantaged and remote users

NGA Standard 0076 (NGA.STND.0076) "GEOINT Imagery Media for ISR" (GIMI), currently in draft, defines a profile of the International Standards Organization/ International Electrotechnical Commission (ISO/IEC) 14496-12 ISO Base Media File Format (ISOBMFF) video/audio standard and the ISO/IEC 23008-12 High Efficiently Image File Format (HEIF) Still Imagery standard. The GIMI Profile is a central element of the NGIIS program. GIMI is expected to replace the National Imagery Transmission Format (NITF) that is widely used within the US Department of Defense for ISR. It is also the likely replacement for STANAG 4545 NATO Secondary Imagery Format (NSIF) with NATO, given the close ties between NITF and NSIF.
