[[pycsw]]
==== OSGeo pycsw

https://pycsw.org[pycsw] is an implementation of the OGC API - Records candidate Standard and the OGC's Catalog Service for the Web (CSW) Standard written in Python. Started in 2010 (more formally announced in 2011), pycsw allows for the publishing and discovery of geospatial metadata via numerous APIs (CSW 2/CSW 3, OpenSearch, OAI-PMH, SRU), providing a standards-based metadata and catalog component of spatial data infrastructures. pycsw is Open Source, released under an MIT license, and runs on all major platforms (Windows, Linux, Mac OS X). pycsw is an official OSGeo Project as well as an OGC Reference Implementation.
pycsw supports numerous metadata content and API standards, including the https://ogcapi.ogc.org/records/[OGC API - Records - Part 1: Core, version 1.0] candidate Standard and its associated specifications. The https://docs.pycsw.org/en/latest/introduction.html#standards-support[official documentation] provides an overview of all supported standards.
