[[results_mapml]]

==== MapML

Several participants worked on this MapML track.

mailto:rpcavaco@gmail.com[Rui Cavaco]'s work (in person at code sprint) had three different 'tracks':

* get a more complete understanding of MapML concept, experimenting with reference implementation polyfill's examples;
* experimenting with JavaScript, possibly extending some polyfill's funcionality;
* understand polyfill suport to projected CRS's such as 'national grids'.

At first experiments it was clear that MapML itself, and the reference implementation polyfill, show several capabilities which manifest themselves when one goes beyond the simplest OSM tiling examples.

Three examples of this: 

* the map-extent element (and the possibility of existing several for each layer);
* the combining of “projection” attribute and of “units” attribute;
* the OSMTILES, CBTILES and other keywords for “projection” or “units”.

The necessity to go through several examples to fully grasp the MapML capability became very clear. 

Also became quite clear that it is not crucial to extend polyfill's functionality, since it is supposed that such functionality should be, sooner or later, transferred to browser's code bases.

So Rui Cavaco's final work was dedicated to JavaScript DOM manipulation using, one of MapML's most interesting features: the ability to, easily, add dynamic changes to web maps. In this case, a real world problem was addressed, the ability to add to and remove from, a web map, at user's request, some municipal-scale themes from Northern Portugal region.

To this purpose a webapp was built using MapML polyfill from https://github.com/Maps4HTML/Web-Map-Custom-Element[Maps4HTML] and https://panel.holoviz.org/[Holoviz Panel] Python web framework.

Slides describing this work in more detail can be found https://github.com/rpcavaco/panel_mapml/blob/main/MapML_Experiments.pdf[here]. The code repository on GitHub you can find it https://github.com/rpcavaco/panel_mapml[here].

On the other hand, UAB-CREAF participated in the spring by contributing their MiraMon Map Server. This application has been addapted to OGC API Maps and Tiles during previous sprints. In this particular sprint, two modifications were introduced to include support to MapML. 

* A request to a /collections/{collectionId}/map with no extra parameters that negociates HTML, will result in the creation of an HTML page that includes a MapML section to preview the map. This results in an HTML interactive page.
* A request to a /collections/{collectionId}/map with no extra parameters that negociates MapML, will result in a MapML document that can be visualized in Chrome if the rigth add-in has been previously setup.

In both cases the map API is used twice:

* It produces the initial respond to the "minimalistic" map request (with no parameters) asking for a the HTML or MapML representation of the collection.
* The MapML content uses the URL template mechanims to get a PNG map of the current view and the subsequent views that the user will generate by panning ans zooming into the map.

The following code is common to both MapML responses (HTML or MapML versions). Please note that the OGC Map API is used to generate the PNGs maps. This demonstrates that MapML can use the new OGC API Maps with no modification in the current especification.
[source]
----
  <map-extent units="WGS84" label="etopo2" checked="checked">
    <map-input name="z" type="zoom" min="1" max="15"></map-input>
		<map-input name="w" type="width"></map-input>
		<map-input name="h" type="height"></map-input>
		<map-input name="xmin" type="location" units="pcrs" position="top-left" axis="easting" ></map-input>
		<map-input name="ymin" type="location" units="pcrs" position="bottom-left" axis="northing" ></map-input>
		<map-input name="xmax" type="location" units="pcrs" position="top-right" axis="easting" ></map-input>
		<map-input name="ymax" type="location" units="pcrs" position="top-left" axis="northing" ></map-input>
		<map-link rel="image" tref="https://www.ogc3.grumets.cat/cgi-bin/world/miramon.cgi/collections/etopo2/map?crs=http://www.opengis.net/def/crs/OGC/1.3/CRS84&amp;bbox-crs=http://www.opengis.net/def/crs/OGC/1.3/CRS84&amp;bbox={xmin},{ymin},{xmax},{ymax}&amp;width={w}&amp;height={h}&amp;f=PNG&amp;transparent=true"></map-link>
  </map-extent>
----

