
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[.preface]
== Abstract

The subject of this Engineering Report (ER) is a code sprint that was held from November 29th to December 1st, 2022 to advance OGC API Standards that relate to web mapping, and others that relate to styling and symbology encoding standards. The code sprint was hosted by the Open Geospatial Consortium (OGC) and EuroGeographics. The code sprint was sponsored by Ordnance Survey (OS), and was held as a hybrid event with the face-to-face element hosted at the Mundo Madou centre  in Brussels, Belgium.


[.preface]
== Executive Summary

The mechanisms through which maps are delivered across the Internet have evolved significantly over the past two decades. Advancement of such mechanisms has been driven by a combination of factors, for example, new data formats have emerged, the SWaP-C (size, weight, power, and cost) of the devices has improved, and the capabilities of web browsers have been enhanced by improvements brought by HTML5. This means that some of the functionality that web mapping applications previously could not implement in a standardized way, are now becoming increasingly common.

To support the development of OGC API Standards that standardize many of the new capabilities available to web mapping applications, the Open Geospatial Consortium (OGC) and EuroGeographics hosted the 2022 Web Mapping Code Sprint from November 29th to December 1st, 2022. The event was sponsored by OGC Strategic Member, Ordnance Survey. The code sprint was held as a hybrid event, consisting of a virtual element hosted on the OGC’s Discord environment and an in-person element hosted by EuroGeographics in Brussels, Belgium.

Code Sprints experiment with emerging ideas in the context of geospatial Standards, help improve interoperability of existing Standards by experimenting with new extensions or profiles, and are used for building proofs-of-concept to support standards-development activities and the enhancement of software products. Non-coding activities such as testing, working on documentation, or reporting issues are also conducted during a code sprint. In addition, the code sprints’ mentor stream provides an excellent opportunity to onboard developers new to the Standards.

The 2022 Web Mapping Code Sprint focused on the following:

* https://ogcapi.ogc.org/tiles[OGC API – Tiles] Standard: This Standard describes API building blocks that can enable implementations to serve map tiles, vector tiles (tiled feature data) or tiled coverage data.
* https://ogcapi.ogc.org/maps[OGC API – Maps] candidate standard: This candidate Standard describes API building blocks that can enable implementations to serve spatially referenced and dynamically rendered electronic maps.
* https://ogcapi.ogc.org/styles[OGC API – Styles] candidate Standard: This candidate Standard describes API building blocks that can enable implementations to manage and fetch styles that consist of symbolizing instructions that can be applied by a rendering engine to features and/or coverages.
* and various Styles & Symbology Encodings (e.g. SLD, SymCore, etc)

The mentor stream of the code sprint featured https://github.com/opengeospatial/developer-events/wiki/Web-Mapping-Code-Sprint#mentor-streams[two tutorials], about understanding and using one server side and one client side implementation of OGC API - Tiles. They were both well attended, both in-person and online. The mentor stream also included two onboarding sessions, focused on collaborating in software projects that implement the standards.

The code sprint successfully facilitated the development and testing of prototype implementations of OGC API Standards, including  candidate Standards, that relate to web mapping. Further, the code sprint provided a foundation for the development of the next version of the Symbology Core Standard. Sprint participants were able to provide feedback directly to the editors of the Standards and the editors were able to clarify any issues encountered by the sprint participants. The code sprint also raised awareness about the Standards. The code sprint therefore met all of its objectives.

The OGC is an international consortium of more than 500 businesses, government agencies, research organizations, and universities driven to make geospatial (location) information and services FAIR — Findable, Accessible, Interoperable, and Reusable. The consortium consists of Standards Working Groups (SWGs) that have responsibility for designing a candidate Standard prior to approval as an OGC Standard and for making revisions to an existing OGC Standard. The sprint objectives for the SWGs were to:

*	Create awareness about OGC Standards;
*	Develop prototype implementations of OGC Standards, including implementations of draft OGC Application Programming Interface (API) Standards;
*	Test the prototype implementations;
*	Provide feedback to the Editor about what worked and what did not; and
*	Provide feedback about the Standards and candidate Standards.


EuroGeographics is a not-for-profit organization that represents many of the National Mapping, Cadastral and Land Registration Authorities across Europe. The organization facilitates access to data, services, and expertise, as well as supporting the sharing of knowledge across the continent. The organization also publishes a product called Open Maps for Europe, which provided a useful resource for sprint participants. For example, within the first day of the code sprint, the sprint participants had implemented an OGC API -Maps façade in front of a Web Map Service (WMS) that was serving maps from the https://eurogeographics.org/open-maps-for-europe/[Open Maps for Europe] product.

Ordnance Survey (OS) is the National Mapping Agency of Great Britain. OS publishes printed and digital maps, as well as offering access to the maps and data through a variety of APIs. In September 2022, OS launched the https://osdatahub.os.uk/docs[OS NGD API] suite of products that implement a number of OGC API Standards. The Web Mapping Code Sprint therefore provided an opportunity for OS to directly support the advancement and implementation of the OGC API Standards on which the new OS NGD API products are built. The code sprint also provided an opportunity for OS engineers to directly engage with the editors of the Standards. Such access to editors and SWG members greatly accelerates development of applications.

This engineering report makes the following recommendations for future innovation work items:

* Prototyping and demonstration of support for the querying of coverages in HTML Previews of coverage tiles
* A testbed activity to implement the prototype Symbology Core v2.0 would help to evaluate support for the various use cases identified in this sprint
* A testbed activity to evaluate options for access control across OGC API Standards (covering at least the Features, Records, Tiles, and Styles APIs)
* A testbed activity applying the ISO 19135 standard to the registration and management of styles through OGC API - Styles
* A testbed activity analysing the potential for consistent modification and harmonization of different stylesheets (e.g. SLD, Mapbox styles, ArcGIS, MapInfo)

The sprint participants also made the following recommendations for things that the SWGs should consider:

* A code sprint focused on general security/access control issues, across OGC API and broader OGC Standards
* Design an approach for supporting 'Cancel' requests, so that long-running jobs can be terminated as users zoom or pan across a map
* A user guide for OGC API - Tiles would help to accelerate uptake (e.g. describing how to build static tile servers in the Cloud)
* A future version of the OGC API - Tiles Standard could relax or remove the requirement that the tileset list URL ends with `/tiles`


== Submitters

All questions regarding this document should be directed to the editor or the contributors:

[%unnumbered]
[options="header"]
|===
| Name | Organization | Role
|Gobe Hobona| Open Geospatial Consortium | Editor
|Joana Simoes | Open Geospatial Consortium |Editor
|Andreas Matheus	|	Secure Dimensions	|	Contributor
|Antonio Cerciello	|	OSGeo |	Contributor
|Clemens Portele	|	interactive instruments GmbH	|	Contributor
|Erwan Bocher	|	CNRS (National Center for Scientific Research) |	Contributor
|Francesco Bartoli	|	OSGeo |	Contributor
|Iván Sánchez Ortega	|	OSGeo |	Contributor
|Jérôme Jacovella-St-Louis	|	Ecere Corporation |	Contributor
|Joan Maso |	UAB-CREAF	|	Contributor
|Keith Pomakis	|	MariaDB	|	Contributor
|Michael Gordon |	Ordnance Survey	|	Contributor
|Núria Julià Selvas |	UAB-CREAF	|	Contributor
|Olivier Ertz	|	HEIG-VD (School of Management and Engineering Vaud) |	Contributor
|Oscar Andrés Díaz	|	GeoSolutions |	Contributor
|Prajwalita Chavan 	|	IIT Bombay |	Contributor
|Robin Houtmeyers	|	Hexagon |	Contributor
|Tim Schaub |	Planet Labs PBC |	Contributor
|Tom Crauwels	|	Hexagon |	Contributor
|Tom Kralidis 	|	Meteorological Service of Canada	|	Contributor
|===
