
== Terms and definitions

=== API

An Application Programming Interface (API) is a standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application, or service to other applications [adapted from ISO/IEC TR 13066-2:2016].

=== coordinate reference system

A coordinate system that is related to the real world by a datum term name [source: ISO 19111]

=== dataset
a set of data, published or curated by a single agent, and available for access or download in one or more representations (modified from DCAT: https://www.w3.org/TR/vocab-dcat-2/#dcat-scope).

NOTE: A Web API implementing OGC API - Common often gives access to a single dataset which may be comprised of one or more _geospatial data resources_.

=== geospatial data resource
web accessible resource that consists of a set of geospatial data

NOTE: In Web APIs implementing _OGC API - Common - Part 2: Geospatial Data_, geospatial data resources are referred to as collections and are defined in the _collections_ conformance class.

NOTE: _geodata_ is sometimes used in this document as an abbreviation of _geospatial data_

=== geospatial resource aspect
web accessible resource that represents a component of geospatial information (metadata, schemas...) or geospatial data accessed using a particular mechanism and data model (e.g., feature items, tiles, maps, coverages,...) of a more generic geospatial data resource (e.g., a collection)

NOTE: Not to be confused with a web accessible resource representation. While resource representations share the same path and are selected by format negotiation, geospatial aspects use different paths. Commonly a geospatial aspect is a subpath of a geospatial data resource.

=== map tile

_tile_ that contains information in a raster form where the values of cells are colors which can be readily displayed on rendering devices

NOTE: Map tiles are generated in combination with _OGC API - Maps_.


=== OpenAPI Document

A document (or set of documents) that defines or describes an API. An OpenAPI definition uses and conforms to the OpenAPI Specification (https://www.openapis.org)

=== geographic information

information concerning phenomena implicitly or explicitly associated with a location relative to the Earth (source: ISO 19101)


=== map

portrayal of geographic information as a digital image file suitable for display on a computer screen (source: OGC 06-042)


=== portrayal

presentation of information to humans (source: ISO 19117)


=== map tile

_tile_ that contains information in a raster form where the values of cells are colors which can be readily displayed on rendering devices

NOTE: Map tiles are generated in combination with _OGC API - Maps_.

=== tile

geometric shape with known properties that may or may not be the result of a tiling (tessellation) process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

In the context of a 2D _tile matrix_, a _tile_ is one of the rectangular regions of space, which can be uniquely identified by row and column integer indices, making up the tile matrix.

In the context of a geospatial data _tile set_, a _tile_ contains data for such a partition of space as part of an overall set of tiles for that tiled geospatial data.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

NOTE: Tiles are useful to efficiently request, transfer, cache, display, store and process geospatial data for a specific resolution and area of interest, providing deterministic performance and scalability
for arbitrarily large datasets.

NOTE: Tiles can contain a variety of data types, such as grid-based pictorial representations (map tiles), coverage subsets (coverage tiles), or feature-based representations (vector tiles).

=== tile matrix

tiling grid in a given 2D coordinate reference system, associated to a specific scale and partitioning space into regular conterminous _tiles_, each of which being assigned a unique identifier

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

NOTE: Each tile of a tile matrix is uniquely identifiable by a row and a column integer index. The number of rows is referred to as the _matrix height_, while the maximum number of columns is referred to
as the _matrix width_ (the number of columns can vary for different rows in _variable width tile matrices_).

=== tile matrix set

_tiling scheme_ consisting of a set of _tile matrices_ defined at different scales covering approximately the same area and having a common coordinate reference system.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard


=== tile set

a set of _tiles_ resulting from tiling data according to a particular _tiling scheme_

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space, but adapted to clarify that in the context of this document, a tile set refers specifically to a set of tiles containing
data and following a common tiling scheme.


=== Web API

API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]


=== Abbreviated terms

API:: Application Programming Interface
CRS:: Coordinate Reference System
GIS:: Geographic Information System
OGC:: Open Geospatial Consortium
OWS:: OGC Web Services
REST:: Representational State Transfer
