[[conclusions]]
== Conclusions

The code sprint successfully facilitated the development and testing of prototype implementations of OGC API Standards, including  candidate Standards, that relate to web mapping. Further, the code sprint provided a foundation for the development of the next version of the Symbology Core Standard. Furthermore, sprint participants were able to provide feedback directly to the editors of the Standards, whereas the editors were able to clarify any issues encountered by the sprint participants. The code sprint also raised awareness about the Standards. The code sprint therefore met all of its objectives.

=== Future Work

The sprint participants made the following recommendations for future innovation work items:

* Prototyping and demonstration of support for the querying of coverages in HTML Previews of coverage tiles;
* A testbed activity to implement the prototype Symbology Core v2.0 would help to evaluate support for the various use cases identified in this sprint;
* A testbed activity to evaluate options for access control across OGC API Standards (covering at least the Features, Records, Tiles, and Styles APIs); and
* A testbed activity analyzing the potential for consistent modification and harmonization of different stylesheets (e.g., SLD, Mapbox styles, ArcGIS, MapInfo).

The sprint participants also made the following recommendations for things that the SWGs should consider:

* A code sprint focused on general security/access control issues, across OGC API and broader OGC Standards;
* Design an approach for supporting 'Cancel' requests, so that long-running jobs can be terminated as users zoom or pan across a map;
* A user guide for OGC API - Tiles would help to accelerate uptake (e.g., describing how to build static tile servers in the Cloud); and
* A future version of the OGC API - Tiles Standard could relax or remove the requirement that the tileset list URL ends with `/tiles`.

It is envisaged that the SWGs will consider the above-listed recommendations for future work items.
