[[geoapi_results]]
==== OGC GeoAPI

The work done during this code sprint was not on GeoAPI itself, but on a usage of it.
GeoAPI is the interface between the https://github.com/IOGP-GIGS/GIGSGeoAPI[Java runner of GIGS tests]
(Geospatial Integrity of Geoscience Software) and https://github.com/OSGeo/PROJ-JNI[PROJ-JNI].
Both projects have been updated for enabling the execution of a greater range of GIGS tests on PROJ.
The changes consisted in upgrading the way that client codes discover GeoAPI implementations.
That discovery is done through the Java _Service Providers_ mechanism.
However, that mechanism changed significantly between Java 8 and Java 9.
The new mechanism in Java 9, in addition to being more secure,
also provides more flexibility in the way to discover services.
This flexibility has been exploited during this code sprint for filling some holes in the GIGS test coverage.

The Apache SIS project, which is another GeoAPI implementation, has not yet been updated to Java 9+ modularization.
That update will take more time because SIS is made of many modules, while PROJ-JNI is a single module.
But this testbed experimented how the work can been done.
An outcome of this testbed is that a small change will be needed in GeoAPI for working
with the more security-constrained way that Java 9+ discovers services and resources.
