==== GeoNetwork

===== Support for OGC API Records in GeoNetwork-UI

Participants from Camptocamp worked on the following tasks related to the User Interface (UI) of GeoNetwork:

* creating an abstraction level between the search-related components of GeoNetwork-UI and the actual search backend used for metadata records; and
* implementing a search backend compatible with OGC API - Records.

Eventually, a GeoNetwork-UI application such as the https://github.com/geonetwork/geonetwork-ui/tree/main/apps/datahub[Datahub] could be able to
provide a search interface over any implementation of OGC API - Records. Some features currently provided by GeoNetwork 4.x might not be available anymore, but
basic search functionalities should still offer a valuable user experience.

Pull request: https://github.com/geonetwork/geonetwork-ui/pull/464

===== Filtering improvements to GeoNetwork-UI

Participants from Astun Technology worked on the following task related to the GeoNetwork-UI 
application https://github.com/geonetwork/geonetwork-ui/tree/main/apps/datahub[Datahub]:

* expanding the available search filters for Datahub to include metadata standards and INSPIRE keywords.

Pull request: https://github.com/geonetwork/geonetwork-ui/pull/477
