==== OGC API - Environmental Data Retrieval

In the OGC MetOcean Domain Working Group (DWG) there is interest in establishing an OGC API approach for Publish/Subscribe (Pub/Sub) operations. This is because alerts have to be sent out instantly when severe weather events occur. Members of the MetOcean DWG have been developing a Discussion Paper on Pub/Sub operations which was presented at the OGC Member Meeting in Frascati, Italy in February 2023. It is envisaged that the Discussion Paper will lead to the specification of a conformance class in the https://ogcapi.ogc.org/edr/[OGC API - Environmental Data Retrieval (EDR)] standard that can also be used by other OGC API Standards as well.

The Discussion Paper describes a number approaches of how to support event-driven functionality in OGC API Standards. The Discussion Paper specifies a prototype API. The next step is turning that prototype into a conformance class. The basic premises behind the specification is to be generic. The specification recommends use of AsyncAPI to advertize an event-driven capability. The specification also recommends use of a well-known encoding, for example, JSON. Finally, the specification recommends use of the endpoint of the building blocks used for OGC API when advertizing the event-driven capability.

An initial attempt at generic conformance classes is being developed in a https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/426[draft pull request to OGC API - EDR].

The generic nature of the draft at the time of the code sprint is a challenge for subscribers as the content of the messages is undefined. As a result, different publishers will design messages in different ways and provider-specific subscription clients have to be developed. This resulted in a https://github.com/opengeospatial/MetOceanDWG/issues/10#issuecomment-1521675694[proposal for adding a new conformance class for a generic message payload], which was added to the OGC API - EDR pull request after the code sprint.

During the code sprint pygeoapi was updated with an implementation of the draft Pub/Sub extension.

Work on a new ldproxy Pub/Sub module for feature resources was started based on the draft Pub/Sub extension. Two open-source Java libraries for MQTT were analyzed (Eclipse Paho and HiveMQ). HiveMQ was selected for the development, mainly because of its support for reactive programming. Only the initial framework was set up during the code sprint. The work will be continued in OGC Testbed-19.