[[ogc_styles_and_symbology_results]]

==== OGC Styles and Symbology

During this code sprint the sprint participants worked on the JSON encoding of the OGC Styles & Symbology draft candidate Standard. The work included:

* presenting the standard in detail to the https://geostyler.org/[GeoStyler] team who then provided the editors of the standard with valuable feedback;
* a new example styling for polygonal features;
* a new JSON Schema for the encoding; and
* addition of some descriptive text for the section.

A number of GitHub Issues were created as a result of this work. This included a https://github.com/opengeospatial/styles-and-symbology/issues/41[GitHub Issue] to fix the direction of the composition arrow in Unified Modeling Language (UML) class diagrams in the draft candidate Standard. This also included an https://github.com/opengeospatial/styles-and-symbology/issues/42[issue] for updating of the naming of the enumerations of the `RelationalOperator` between the table and the UML class diagram to improve consistency. Another https://github.com/opengeospatial/styles-and-symbology/issues/45[issue] created was for addition of capabilities required for completeness. Pull requests were also created for https://github.com/opengeospatial/styles-and-symbology/pull/43[fixing editorial issues] and formatting the https://github.com/opengeospatial/styles-and-symbology/pull/44[CartoSym JSON schema].
