[[openlayers_results]]
==== OSGeo OpenLayers

OpenLayers contributors used time at the code sprint to discuss topics related to vector feature styling and rendering.  The discussions were to support on-going development of a new WebGL vector renderer, as well as work on a new internal feature representation and style encoding syntax to be supported by the new renderer.

OpenLayers currently allows for very flexible feature style generation by allowing users to provide an arbitrary function to generate symbolizers at render time.  This limits the efficiency of vector rendering as the library is currently unable to evaluate these style functions outside the main thread.  OpenLayers contributors made good progress, at the code sprint, designing a new encoding for rule-based styling that allows flexibility in providing expressions to generate symbolizer values while still allowing for efficient evaluation of these expressions in a worker or on the Graphics Processing Unit(GPU) of a computer.

OpenLayers contributors will likely plan another dedicated sprint to continue this work and implement the new styling design in the WebGL vector renderer in addition to the existing Canvas (2D) renderer.
