[[pygeometa_results]]
==== OSGeo pygeometa

The pygeometa project https://github.com/geopython/pygeometa/pull/224[added] support for detailed schema capability reporting, so that a client can be aware of which schemas are supported, and whether those schemas have read and/or write support. This was also implemented as pygeoapi plugin, and https://github.com/geopython/demo.pygeoapi.io/commit/9493c5627bbd78351613ecd6b5078936246003d6[made available] as part of the pygeoapi https://demo.pygeoapi.io/master[public demo]. "pygeometa as a service" is used by the https://osgeo.github.io/mdme[live demo] of the mdme project. The schema capability integration was added by mdme as part of the sprint.

The MDME project uses https://koumoul-dev.github.io/vuetify-jsonschema-form[vjsf] internally to render a web based metadata edit form derived from json schema. A visual edit form for MCF has proven to be usefull in yaml oriented metadata workflows for some user groups. Some json schema concepts such as any-of are not supported by vjsf. During the sprint MDME has been improved to prevent the use of any-of and selector patterns having '*'. As mentioned above, import from  iso19139 and export to iso19139, stac, and ogcapi:records (based on a transformation service provided by pygeoapi/pygeometa) have been introduced. 
