[[gimi_discussion]]
==== GIMI

The GIMI thread of the code sprint set out to accomplish two groups of tasks. The first group of tasks focused on prototyping an NGIIS Web API that: 

* first, provided random access to GIMI content; 
* second, extended the Web API to support storage of GIMI files; and 
* third, extended the Web API to support updates to an existing GIMI file using random access. 

As described in <<pygeoapi_gimi_results>> and <<gnosis_results>>, the sprint participants were able to prototype capability that demonstrated how implementations of OGC API - Tiles and OGC API - Coverages could provide random access to content from GIMI files. The ability to support storage of GIMI files through an implementation of OGC API - Processes was prototyped after the three-day code sprint and is documented in <<update_storage>>. The ability to update a GIMI file through an OGC API was not demonstrated in this code sprint due to time constraints and limitations of some of the key HEIF libraries. The sprint participants were able to record https://github.com/opengeospatial/developer-events/issues/75[five issues] in libheif, some of which have since been fixed by the maintainers of libheif. The sprint participants were also able to propose changes to mp4box.js and misb.js through pull requests.

The second group of tasks focused on client applications: 

* first, implementation of a client that can generate GIMI files with different types of imagery and store them using the NGIIS Web API; and
* second, implementation of client applications that can access GIMI data, show/display content id, timing, and security information. 

As described in <<results_gimi_open_source_libraries>>, a custom application with a variety of libraries was used in the generation of GIMI files. The resulting GIMI files used HEVC (H.265), JPEG 2000, and uncompressed encodings. Additional experimentation was conducted as documented in <<results_pixalytics_gimi>>. Two web-browser based applications were configured to read and display GIMI files, namely MiraMon (described in <<gimi_MiraMonWebBrowser_results>>) and the web-gimi-viewer (described in <<geo_heif_viewer_results>>). In addition to the the web-browser based applications, a plug-in for the QGIS Desktop application was implemented for reading GIMI files as described in <<results_gimi_open_source_libraries>>.