[[jsonfg_discussion]]

==== JSON-FG

Several different types of applications were implemented or configured to support JSON-FG during the Code Sprint. Implementations included validators (linters), client-side applications, and server-side applications. The implementations and discussion led to a number of questions being logged on the SWG's GitHub repository (GitHub Issues 105 to 109). There were also some questions asked by developers that were getting started with JSON-FG during the code sprint. This suggests that the release of JSON-FG has to be accompanied by educational workshops and training to help the community adopt the standard. Messaging, especially in relation to the association with GeoJSON, will need to be clear.

One of the topics discussed by sprint participants was JSON-FG support for different coordinate reference systems. They also discussed the GeoJSON compatibility. Since the sprint took place in London, the British National Grid (EPSG:27700) was used as the coordinate reference system in example requests to an API implementing OGC API - Features. Several participants, for example those from MariaDB and interactive instruments, configured their applications to serve JSON-FG encoded data that was referenced to EPSG:27700. Support for the RD coordinate reference system that is used in the Netherlands was also demonstrated.