[[muddi_discussion]]
==== MUDDI

The work done by multiple sprint participants demonstrated that the MUDDI conceptual model could be used as the basis for implementing databases. MariaDB, Ordnance Survey, Safe Software are some of the participants that implemented databases based on the MUDDI model. The draft JSON-FG and GML schemas of MUDDI that were provided by interactive instruments successfully enabled data to be served through an interface conforming to the OGC API - Features Standard. The same GML schemas were also used by Safe Software to generate MUDDI GML. The analysis by IIT Bombay provided further insight into the similarity of feature properties in synthetic datasets versus those in the draft MUDDI schemas. 

It is clear from the aforementioned implementations of MUDDI that MUDDI can be implemented. However, as the candidate Standard is that of a Conceptual Model, there is a need to specify a Standard for a logical model and data encoding. This need is evidenced by the observation that several developers had to make design-decisions (such as how to represent relationships between tables) regarding how to implement MUDDI during the code sprint (see <<os_muddi_results>> for a description of some of those decisions). There were also some model interpretation decisions that had to be made in discussions with interactive instruments, prior to their generation of the GML schemas, as to what geometries should be used for each feature type. For the purposes of the pilot it was decided to select simple geometries such as points lines or polygons. An encoding standard would formalize some of those design-decisions so that that they become common to all implementations of MUDDI.
