[[ogcapi_discussion]]
==== OGC API Standards

This section discusses findings that apply to multiple OGC API Standards, as well as implications of those findings.

===== Towards a common Publish/Subscribe Event Driven Approach

Activity during the code sprint included implementation of support for the Publish/Subscribe extension of OGC API - EDR. Through collaboration during the code sprint, the approach was also tested with OGC API - Features. Initial discussion was started regarding the possibility of applying the approach in OGC API - Processes and is captured in a https://github.com/opengeospatial/ogcapi-processes/issues/374[GitHub Issue]. It is envisaged that common requirements can be identified and specified once the Publish/Subscribe approach has been tested with three or more OGC API Standards. 

===== Security

Multiple implementations of OGC API Standards demonstrated access control during the code sprint. For example, the Create, Replace, Update, Delete capabilities implemented by interactive instruments in ldproxy were protected through an access control layer. Another example was the CREAF and Secure Dimensions implementation of the STAplus extension of the OGC SensorThings API. The STAplus implementation was protected by an access control layer at the observation and feature level. These implementations, as well as others, demonstrate that OGC API Standards can support a variety of security models. 

===== TBA

TBA