
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[.preface]
== Abstract

The subject of this Engineering Report (ER) is a code sprint that was held from the 14th to the 16th of September 2022 to advance open standards that relate to geospatial metadata and catalogues. The code sprint was hosted by the Open Geospatial Consortium (OGC) and the International Organization for Standardization (ISO). The code sprint was sponsored by Ordnance Survey (OS) and Geonovum, and held as a hybrid event with the face-to-face element hosted at the Geovation Hub in London, United Kingdom.


[.preface]
== Executive Summary

Over the past two decades, standards such as ISO 19115:2003 and the OGC Catalogue Services for the Web (CSW) have been integrated into several Spatial Data Infrastructure (SDI) initiatives at national and international level. These standards leveraged the Extensible Markup Language (XML) which, at the time, was the primary encoding for data exchange across much of Information Technology. In recent times, however, the increasing use of JavaScript Object Notation (JSON) and the uptake of Web Application Programming Interface (API) has meant that modernisation of metadata and catalogues approaches is necessary.

In November 2021, the Open Geospatial Consortium (OGC) and the International Organization for Standardization (ISO) held their first joint code sprint. The success of that first joint code sprint provided the foundation for a second joint code sprint. This Engineering Report (ER) summarizes the main achievements of the second joint code sprint, conducted between September 14th and 16th, 2022. The second code sprint, named the 2022 Joint OGC and ISO Code Sprint - The Metadata Code Sprint, served to accelerate the support of open geospatial standards that relate to geospatial metadata and catalogues. The code sprint was sponsored by Ordnance Survey (OS) at the Gold-level and Geonovum at the Silver-level. The code sprint was held as a hybrid event, with the face-to-face element hosted at the Geovation Hub in London, United Kingdom.

The code sprint focused on the following group of APIs and encodings:

* https://ogcapi.ogc.org/records/[OGC API - Records] candidate standard
* ISO 19115 metadata Standards (i.e., https://www.iso.org/standard/53798.html[ISO 19115-1], https://www.iso.org/standard/67039.html[ISO 19115-2], https://www.iso.org/standard/32579.html[ISO 19115-3])
* OGC Features and Geometries JSON (JSON-FG) candidate standard
* Spatio-Temporal Asset Catalog (STAC), which leverages the OGC API - Features Standard

The OGC is an international consortium of more than 500 businesses, government agencies, research organizations, and universities driven to make geospatial (location) information and services FAIR - Findable, Accessible, Interoperable, and Reusable. The consortium consists of Standards Working Groups (SWGs) that have responsibility for designing a candidate standard prior to approval as an OGC Standard and for making revisions to an existing OGC Standard. The sprint objectives for the SWGs were to:

* Develop prototype implementations of OGC standards, including implementations of draft OGC Application Programming Interface (API) standards
* Test the prototype implementations
* Provide feedback to the Editor about what worked and what did not
* Provide feedback about the specification document

Technical Committee 211 (TC 211) of ISO is responsible for the development and publication of standards that relate to geographic information. As with other ISO committees, TC 211 consists of member nations, as well as liaison partner organizations. TC 211 and OGC have a liaison partnership that enables the organizations to participate in each others activities and also to collaborate of standards development initiatives. The sprint objectives for ISO/TC 211 were:

* Support the development of ISO Standards
* Fix open issues
* Develop new features
* Encourage the implementation of ISO Standards

This engineering report makes the following recommendations for future innovation work items:

* Initiatives to facilitate implementation of JSON-FG (e.g. 3D, cadastral data, etc)
* Initiatives to facilitate implementation of catalogues
* Prototyping of tools for creating metadata (e.g. the automated STAC metadata crawler demonstrated during the sprint)

The engineering report also makes the following recommendations for things that the Standards Working Groups should consider:

* Outreach for JSON-FG
* Code Sprint for designing profiles of JSON-FG for different communities of interest
* Documentation of the different roles of catalogues and API, as well as guidance on when to use them
* Code Sprint on versioning, possibly combining an OGC API Features Part 4 with OGC API Records
* Exploring how to move GeoDCAT forward within OGC


== Submitters

All questions regarding this document should be directed to the editor or the contributors:

[%unnumbered]
[options="header"]
|===
| Name | Organization | Role
|Gobe Hobona| Open Geospatial Consortium | Editor
|Joana Simoes | Open Geospatial Consortium |Editor
|Panagiotis	Vretanos	|	CubeWerx Inc.	|	Contributor
| Núria Julià Selvas |	UAB-CREAF	|	Contributor
| Joan Maso |	UAB-CREAF	|	Contributor
|Clemens Portele	|	interactive instruments GmbH	|	Contributor
|Matthias Mohr	|	WWU Münster	|	Contributor
|Tom Kralidis 	|	Meteorological Service of Canada	|	Contributor
|Byron Cochrane	|	OpenWork Ltd |	Contributor
|Andreas Matheus	|	Secure Dimensions	|	Contributor
|Jeroen Ticheler	|	GeoCat	|	Contributor
|===
