
== Terms and definitions

=== API

An Application Programming Interface (API) is a standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application, or service to other applications (adapted from ISO/IEC TR 13066-2:2016).

=== coordinate reference system

A coordinate system that is related to the real world by a datum term name (source: ISO 19111)

=== OpenAPI Document

A document (or set of documents) that defines or describes an API. An OpenAPI definition uses and conforms to the OpenAPI Specification (https://www.openapis.org)

=== Metadata

information about a resource [source: ISO 19115-1:2014, Amendment 2]

=== Web API

API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]


=== Abbreviated terms

API:: Application Programming Interface
CRS:: Coordinate Reference System
GIS:: Geographic Information System
OGC:: Open Geospatial Consortium
OWS:: OGC Web Services
REST:: Representational State Transfer
