[[discussion]]
== Discussion

==== Harmonization between STAC and OGC API Records

Although both STAC and OGC API - Records use GeoJSON for encoding metadata, alignment is necessary in order to improve metadata exchange. STAC has an Asset construct and OGC API - Records uses a Link construct. If OGC API - Records adopts the use of Assets then there is a need to be clear about the difference between Assets and Links.

There is a perception that STAC is focused on Earth Observation (EO). The Record metadata model which is specified in OGC API - Records is supposed to cover more than just EO. The idea with the Records metadata model is that it offers a small set of generic properties that can be used to describe anything. This makes it possible for communities of interest to extend the model to support their particular use case. The way that one uses a Record depends on how the person wants to make the resource discoverable. This impacts how the record is created and how it is linked with other Records.

There is a conflict between some elements where they may have the same name but different meaning (e.g. created and updated dates). The Records metadata model targets a the resource, whereas STAC targets a distribution. This creates a challenge for Records because it would be impossible to give different dates of update for different distributions of the same resource. To align OGC API Records with STAC there would be a need to change 'record-created' and 'record-updated' fields to simply 'created' and 'updated'. Other potential opportunities for alignment include the use a 'roles' element in the links section.

Every Item has a link to one collection. You could create a hierarchy using a collection. One level of collection and then the items are records. In this context, STAC and OGC API - Records are already aligned.

The lessons identified regarding harmonization can be summarized as:

* Modify the create and updated fields by removing them from the Record class add them to the links. This would improve alignment with STAC.
* In some cases it may be necessary to use either STAC or OGC API - Records, depending on the needs of the community of interest.



=== STAC

STAC 'root' link relation types need to be further clarified as OGC link relation types or Compact URIs (CURIEs).

=== JSON-FG

TBA

=== Summary of Lessons Identified

The following are the immediate lessons identified by the sprint participants:

==== Harvesting

* It's important to be clear about what harvesting means.
* Keeping the metadata close to the data is more efficient than copying the metadata to a separate server.
* Ideally harvesting would be of selected bits of metadata instead of the complete metadata record.
* There are different types of harvesting, in some cases there may be some processing needed. One type of approach means harvesting the discovery metadata.
* In some cases, augmented metadata may need to be pushed back to the source.
* We need to be clear about what we mean when we say "close to the data".

==== Transactions

* Currently, OGC API - Features - Part 4: Create, Replace, Update and Delete defines two requirements classes ("Create/Replace/Delete", and "Update").  It would be valuable to split the "Create/Replace/Delete" requirements class into 3 separate classes, to allow for finer granularity for resource management.


==== The consideration of adding JSON-FG as another encoding for OGC API Records

* There is not an identified need for JSON-FG encodings in OGC API Records and STAC. However, it could be identified in the future.
* The canonical time is a top-level element in JSON-FG. This could be useful for OGC API Records.
* More feedback is needed

==== ISO metadata and OGC API Records

* Expressing ISO 19115 metadata in OGC API Records should focus on discovery elements.
* Initial prototyping has been focused on Keywords to Themes
* What is needed is a profile that enables us to work with ISO 19115
* Content negotiation by profile could be useful.
* The incremental approach would be useful.
* It may be necessary to also design a JSON profile of ISO 19139 as well.
* There are various considerations relating to alignment with ISO 19115 e.g. alignment with DCAT
* We need to balance how deeply we want to represent ISO metadata in JSON

The following section presents the conclusions.
