[[discussion]]
== Discussion

==== Harmonization between STAC and OGC API Records

Although both STAC and OGC API - Records use GeoJSON for encoding metadata, alignment is necessary in order to improve metadata exchange. STAC has an Asset construct and OGC API - Records uses a Link construct. If OGC API - Records adopts the use of Assets then there is a need to be clear about the difference between Assets and Links.

There is a perception that STAC is focused on Earth Observation (EO). The Record metadata model which is specified in OGC API - Records is supposed to cover more than just EO. The idea with the Records metadata model is that it offers a small set of generic properties that can be used to describe anything. This makes it possible for communities of interest to extend the model to support their particular use case. The way that one uses a Record depends on how the person wants to make the resource discoverable. This impacts how the record is created and how it is linked with other Records.

There is a conflict between some elements where they may have the same name but different meaning (e.g. created and updated dates). The Records metadata model targets a the resource, whereas STAC targets a distribution. This creates a challenge for Records because it would be impossible to give different dates of update for different distributions of the same resource. To align OGC API Records with STAC there would be a need to change 'record-created' and 'record-updated' fields to simply 'created' and 'updated'. Other potential opportunities for alignment include the use a 'roles' element in the links section.

It was also determined that the STAC 'root' link relation types need to be further clarified as OGC link relation types or Compact URIs (CURIEs).

Every Item has a link to one collection. You could create a hierarchy using a collection. One level of collection and then the items are records. In this context, STAC and OGC API - Records are already aligned.

The lessons identified regarding harmonization can be summarized as:

* Modify the create and updated fields by removing them from the Record class add them to the links. This would improve alignment with STAC.
* In some cases it may be necessary to use either STAC or OGC API - Records, depending on the needs of the community of interest.
* Clarify definition and intent of STAC 'root' link relation types in relation to OGC link relation types or Compact URIs (CURIEs)

==== Harvesting

It is important to be clear about what harvesting means. It is the complementary operation to Transactions. In Transactions you push a record to the catalogue, that requires the client to take the source and push that to the catalogue. For harvesting, you tell the catalogue "here is the resource" and the catalogue extracts the metadata and takes care of the rest. It is always possible that the catalogue will go to the resource and not know what to do with it. In the CSW standard there was support for harvesting. With harvesting the onus is on the catalogue to determine how to transform the resource and create the record for that resource.

Is is also a question, if you point it to something, should we leave that to the harvestor? The simplest approach is to leave it up to the harvestor once the client has directed the harvestor towards a resource. In the CSW ebrim model there was guidance of how to harvest a GetCapabilities response. As a minimum they would look for all of the fields that are in the record and try to populare those. More guidance would be needed for OGC API Standards, for example how deep to go in navigating the link graph.

In certain instances, for example in the local Catalogue offered by OGC API Records, we cover that with local instance resources. This supports a situation where an entity might have a catalogue but the catalogue might have records about a separate entity.

An example workflow would be to: Submit a harvest request, with a prefer header, then the request would be executed synchronously or asynchronously, then it would notify you that it is initiated a job meaning that the client application can monitor the job and retrieve the results when the job is complete. It could then leverage an approach similar to that demonstrated by Secure Dimensions. To achieve such a workflow, there is a need to define an API for harvesting resources or collections of resources. Providing guidance on how to crawl an OGC API resource tree and to harvest the resources it offers.


The lessons identified regarding harmonization can be summarized as:

* It is important to be clear about what harvesting means.
* Keeping the metadata close to the data is more efficient than copying the metadata to a separate server.
* Ideally harvesting would be of selected bits of metadata instead of the complete metadata record.
* There are different types of harvesting, in some cases there may be some processing needed. One type of approach means harvesting the discovery metadata.
* In some cases, augmented metadata may need to be pushed back to the source.
* We need to be clear about what we mean when we say "close to the data".

=== ISO 19115 metadata and OGC API Records

The lessons identified regarding ISO 19115 metadata and OGC API Records can be summarized as:

* Expressing ISO 19115 metadata in OGC API Records should focus on discovery elements.
* Initial prototyping has been focused on Keywords to Themes
* What is needed is a profile that enables us to work with ISO 19115
* Content negotiation by profile could be useful.
* The incremental approach would be useful.
* It may be necessary to also design a JSON profile of ISO 19139 as well.
* There are various considerations relating to alignment with ISO 19115 e.g. alignment with DCAT
* We need to balance how deeply we want to represent ISO metadata in JSON

The following section presents the conclusions.



=== JSON-FG

TBA

=== Transactions

The lessons identified regarding transactions can be summarized as:

* Currently, OGC API - Features - Part 4: Create, Replace, Update and Delete defines two requirements classes ("Create/Replace/Delete", and "Update").  It would be valuable to split the "Create/Replace/Delete" requirements class into 3 separate classes, to allow for finer granularity for resource management.


=== Addition of JSON-FG as another encoding for OGC API Records

The lessons identified regarding addition of JSON-FG as another encoding for OGC API Records can be summarized as:

* There is not an identified need for JSON-FG encodings in OGC API Records and STAC. However, it could be identified in the future.
* The canonical time is a top-level element in JSON-FG. This could be useful for OGC API Records.

More feedback from implementers is needed in order to improve understanding of the potential use of JSON-FG in OGC API - Records.
