[[conclusions]]
== Conclusions

This was the first hybrid code sprint (consisting of both in-person and remote elements) organized by the OGC in more than two years, due to the pandemic. A record number of participants registered to attend the code sprint, exceeding pre-pandemic registration numbers. There were, however, more remote participants than those attending in-person. This suggests that there continues to be significant interest in code sprints, and that the online collaboration environment should continue to be used post-pandemic.

The code sprint facilitated the development and testing of prototype implementations of OGC and ISO Standards that relate to geospatial metadata and catalogues. The code sprint also enabled the participating developers to provide feedback to the editors of candidate standards. The code sprint therefore met all of its objectives and achieved its goal of accelerating the support of open geospatial standards that relate to geospatial metadata and catalogues.

=== Future Work

The sprint participants made the following recommendations for future innovation work items:

* Initiatives to facilitate implementation of JSON-FG (e.g., 3D, cadastral data, etc);
* Initiatives to facilitate implementation of catalogues; and
* Prototyping of tools for creating metadata (e.g., the automated STAC metadata crawler demonstrated during the sprint),

The sprint participants also made the following recommendations for things that the SWGs should consider:

* Outreach for JSON-FG;
* Code Sprint for designing profiles of JSON-FG for different communities of interest;
* Documentation of the different roles of catalogues and API, as well as guidance on when to use them;
* Code Sprint on versioning, possibly combining an http://docs.ogc.org/DRAFTS/20-002.html[OGC API - Features - Part 4] with http://docs.ogc.org/DRAFTS/20-004.html[OGC API - Records]; and
* Exploring how to move GeoDCAT forward within OGC.

It is envisaged that the SWGs will consider the above-listed recommendations for future work items.
