[[geonovum_results]]
==== Geonovum testing of JSON-FG support in GDAL

Sprint participants from Geonovum worked on testing the JSON-FG candidate Standard and evaluating GDAL's implementation of the candidate Standard. To facilitate the evaluation, they specified a series of test scenarios that includes tests of transformation of GML to JSON-FG, GeoPackage to JSON-FG and transformation from 3D data formats to JSON-FG. A more detailed discussion of the tests and their results is presented in an associated report <<geonovum_report>>. Although the tests did not reveal any bugs nor issues found in GDAL's support of JSON-FG, there were a number of findings that could inform future versions of GDAL.

The tests were applied to source data that contained features that were referenced to the Dutch coordinate reference system Rijksdriehoeks (RD). During transformation of feature data to JSON-FG, by default GDAL creates a geometry member that has coordinates that a referenced to WGS84. Further, also by default, GDAL creates a place member with coordinates obtained from the source data during transformation of feature data to JSON-FG. Although this conforms with the JSON-FG candidate Standard, it may not be what some users expect.

One of the findings was that when GDAL cannot identify a source property for the temporal information, it fills the time member of the JSON-FG file with a null value. There does not appear to a way to point GDAL at an appropriate source for filling the time member. However, as GDAL looks for an element called `time`, `time_start`, or `time_end`, it is possible to use a GDAL tool called ogr2ogr to remap the properties of the source data to an output property that has a name that GDAL expects (e.g. time). Another finding was that there is currently no apparent option to have GDAL create a JSON-FG file that references a JSON Schema file that describes the featureSchema.


