==== OGC API - Environmental Data Retrieval


The OGC API - Environmental Data Retrieval (EDR) team and PubSub enthusiasts provided two 5-minute pitch presentations, a mentor session one breakout which focused on Publish-Subscribe workflows for EDR and other OGC API specifications.

The 5-minute pitch presentations focused on Part 1: Core and Part 2: Publish-Subscribe capabilities to help position the subsequent mentor and breakout sessions.

The EDR PubSub mentor session included demonstrations from the joint Open Software and Open Standards Code Sprint between OGC/OSGeo/ASF that was held in Lausanne during the month of April 2023 (<<OGC23-025>>), as well as a demo from NOAA demonstrating PubSub integration with EDR.

A breakout session was also held, focusing on technical details of EDR Part 2.

An ldproxy PubSub demo was given connecting to the WMO WIS2 Global Broker, triggering notification observations into an OGC API - Features collection as well as an additional ldproxy broker.  Observations were made available using the OGC API endpoint structure with a prefix for a given server and suffix for a specific observed property.  Security was also demonstrated by way of using OpenID Connect.

Discussions included:

* Links requirements as discussed in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/451#issuecomment-1787420407[Issue 451]
  * adding a `channel` property to a link object is valuable for efficient binding capabilities for PubSub aware clients
  * non-aware clients would simply be presented a link to a PubSub broker without further context
    * this is what the AsyncAPI document is there for (at the landing page, etc.)
  * addition of the ability to cross-reference collection identifiers from an AsyncAPI document
    * `channels.*.x-ogc-api-collection.url`, for example
  * update link requirement to be a permission to facilitate PubSub aware client interoperability
    * done in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/464[Pull Request 464]

* Channels requirements as discussed in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/452#issuecomment-1787419817[Issue 452]
  * is the OGC API endpoint topic structure enough?
    * The Testbed-19 ldproxy demonstration prefixed topics with tokens to help make the topics unique, which is valuable in the context of broker message aggregation
    * consideration of filters as part of a topic
      * could be advanced functionality
  * turn channels requirement into separate conformance class
    * done in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/465[Pull Request 465]

* Message payload:
  * should make clear that if the message payload is an item, then the `id` property should persist.  Else, if a notification, then the `id` property would be a GUID.

* Cross SWG engagement and longer-term PubSub SWG activities
  * PubSub is a valuable capability for numerous OGC APIs
    * Connected Systems
    * Features: feature transactions
    * Processes: subscribing to async jobs channels, new processes
    * Records: aggregation/metadata ingest/publication
    * Common: collections publishing data updates (e.g. publication of new NWP model run for EDR or Maps)

  * engage with SWGs to determine PubSub approach to notify workflow/patterns on changes to resources

A live demo was given which exemplified the capabilities of PubSub as a workflow for metadata catalogue management.
