==== OGC API - Records

The OGC API - Records team held two breakouts which focused on advancing the specification for OAB review.

Discussions included:

* target of December 2023 for OGC API - Records - Part 1: Core document submission for OAB
  * issue sweep
  * requirements refactoring (shared query parameters)
  * resulting https://github.com/opengeospatial/ogcapi-records/pull/207[ATS refactoring]
  * update on templating links (allowing for using one of `variables` or `varBase`)
  * clarification on `.../items` `q` parameter
  * cleanup and validation of example JSON documents; agreement to tidy up YAML schemas and build CI workflow to ensure schemas are always valid, a bundle is built, and examples are schema valid

* proposal for https://github.com/opengeospatial/ogcapi-records/pull/320[facets]
  * advertising facets and their types (options: separate endpoints, addition of `facet: true` properrites in (`.../queryables`)
  * specifying facets on `.../items` requests
  * agreement to review / approve proposal PR and move forward as an extension

* disussion on federation/distributed search
  * how to address live / distributed search (without metadata harvesting/metadata aggregration)
  * presents issues such as:
    * how to present results (multipart, single document with 'grouped' records [would break GeoJSON interoperability])
    * how to sort results
  * this could be accomplished by a front end client (in Python or JavaScript, for example)
  * some organizations want to provide a unified single catalogue that streamlines the search xperience for users
  * could also be put forth as a best practice on implementation
  * way forward is to put forth a proposal for discussion on requirements
