=== OGC Styles and Symbology

Sprint participants in a breakout session on OGC Styles and Symbology discussed potential Conformance Classes for a new OGC Styles and Symbology Standard. The sprint participants went through the conformance classes to check that none were missing, and found that some were indeed missing. An example of a conformance class that was missing is the Geometry Selection conformance class in relation to the possibility of a symbolizer accessing the underlying geometry to manipulate it. Such a capability could be applied to visualization of https://github.com/opengeospatial/styles-and-symbology/issues/20[proportional symbols], for example, transforming a polygon into a point with the ST_Centroid function (which is defined in the OGC Simple Features 1.2.1 Standard) to draw a proportional symbol.

As several OGC Styles and Symbology SWG members participated in the breakout session, the discussions will help to move towards a version 2.0 "Styles & Symbology Model & Encodings" Standard that includes SymCore and the conceptual/logical definitions of the concrete extensions. The sprint participants started the documentation of the envisaged version 2.0 on GitHub. In terms of naming, the SWG members plan to keep the SymCore name for version 2.0.

In parallel, the sprint participants worked on relevant https://github.com/opengeospatial/styles-and-symbology/labels/Use%20Case[use cases] to test the functional coverage of the proposed model and to relate them to the conformance classes. The use cases are presented in <<annex_a>>. In doing so, the sprint participants tested existing encodings (e.g. GeoCSS) to start imagining the "natural" encoding that could also be documented with Part 1 of the "Styles & Symbology Model & Encodings" candidate standard. The use cases will continue to inspire and inform the work of the SWG for the next few months as the next major milestone will be the 125th OGC Member Meeting, to be held February 2023.
