
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[.preface]
== Abstract

The subject of this Engineering Report (ER) is a code sprint that was held from July 10th to 12th, 2024 to advance the support and development of open standards within the developer community. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Google and supported by Natural Resources Canada (NRCan). The code sprint included activities involving several OGC API Standards and data encoding standards, as well as special tracks on Data Quality & Artificial Intelligence, Map Markup Language (MapML) and Validators.


[.preface]
== Executive Summary

The opportunities presented by Artificial Intelligence (AI) have led to rapid adoption of many AI-related technologies. At the same time, the rapid adoption of AI has highlighted the need for good quality training data to enable the systems to offer effective decision making support. Data quality is therefore an enduring requirement for future geospatial technologies just as it has always been for historic ones. Whereas some of those future geospatial technologies will likely rely on raster data, many others will on vector feature data. Therefore validators capable of checking the validity of vector feature data files are likely to play a key role in an AI-driven future.

The focus of this Engineering Report (ER) is a code sprint that was held from July 10th to 12th, 2024 to advance the support and development of open standards within the developer community. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Google and supported by Natural Resources Canada (NRCan). The code sprint included activities involving several OGC API Standards and data encoding standards, as well as special tracks on Data Quality & Artificial Intelligence, Map Markup Language (MapML) and Validators.

The code sprint was held as a generic code sprint meaning that all OGC working groups were encouraged to participate in the event. As a result, several OGC Standards Working Groups (SWGs) set up teams of developers to collaborate during the three-day event. In addition to providing software developers with an environment for collaborative coding and experimentation, the code sprint also provided opportunities for thought leadership through presentations and tutorials in the Mentor Stream. This made the code sprint a rich environment for knowledge transfer across teams, as well as for nurturing cross-functional teams.

The sprint participants made the following recommendations regarding future Collaborative Solutions and Innovation Program initiatives:

* Initiative for urban Digital Twins
* CDB2 experimentation in the context of Digital Twins
* OGC API - 3D Geovolumes experimentation in the context of Digital Twins
* Experimentation on consistency of metadata frameworks
* An activity building on the ISO metadata activity
* Experimentation on consistency of parameter and schema fragements in APIs
* Prototyping and experimentation on OGC API - Features and Geocoding
* Prototyping of an HTML MapML validator, possibly as a service. See https://github.com/Maps4HTML/validator-mapml for ideas.

The sprint participants made the following recommendations regarding future Standards Program initiatives:

* Discussions on consistency of parameter and schema fragements in APIs
* Discussion possibility of TrainingDML-AI conf class for Records
* Discuss consistency of scale of OMS and APIs
* Addition of a security element in future versions of TrainingDML-AI and other metadata encodings


== Submitters

All questions regarding this document should be directed to the editors or the contributors:

[%unnumbered%]
.Submitters
[options="header"]
|===
|	Name | Organization | Role
|	Gobe Hobona| OGC | Editor
|	Joana Simoes | OGC |Editor
|	Tom Kralidis | OSGeo | Contributor
|	Chris Little | Met Office | Contributor
|	Frank Terpstra | Geonovum | Contributor
|	Maxime Collombin | University of Applied Sciences, Western Switzerland (HEIG-VD)  | Contributor
|	Sam Meek |  Helyx Secure Information Systems | Contributor
|	Rui Cavaco | Norte Portugal Regional Coordination and Development Commission | Contributor
|	Ivana Ivanova | Curtin University | Contributor
|	TBA | TBA | Contributor
|	TBA | TBA | Contributor
|	TBA | TBA | Contributor
|	TBA | TBA | Contributor
|	TBA | TBA | Contributor
|=== 
