
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[.preface]
== Abstract

The subject of this Engineering Report (ER) is a code sprint that was held from July 10th to 12th, 2024 to advance the support and development of open standards within the developer community. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Google and supported by Natural Resources Canada (NRCan). The code sprint included activities involving several OGC API Standards and data encoding standards, as well as special tracks on Data Quality & Artificial Intelligence, Map Markup Language (MapML) and Validators.


[.preface]
== Executive Summary

The rapid adoption of Artificial Intelligence (AI) has highlighted the need for good quality training data to enable the systems to offer effective decision making support. Data quality is therefore a critical requirement for future geospatial technologies just as it has always been for historic ones. Whereas some of those future geospatial technologies will likely rely on raster data, many others will rely on vector feature data. Therefore, validators capable of checking the validity of vector feature data files are likely to play a key role in an AI-driven future.

The focus of this Engineering Report (ER) is a code sprint that was held from July 10th to 12th, 2024 to advance the support and development of open standards within the developer community. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Google and supported by Natural Resources Canada (NRCan). The code sprint included activities involving several OGC API Standards and data encoding standards, as well as special tracks on Data Quality & AI, Map Markup Language (MapML) and Validators. Other activities at the code sprint were related to OGC CoverageJSON, OGC SensorThings API WebSub Extension, OGC API — Records, OGC API - Features, and OGC Styles and Symbology.

The MapML special track of the code sprint sought to prototype integration of a MapML viewer into implementations of OGC API Standards. The MapML specification extends the semantics of several HTML Standard elements, and specifies a small set of new, mapping-specific elements, in the http://www.w3.org/1999/xhtml[HTML namespace]. This engineering report concludes that the sprint participants proved that MapML has a role to play in the geospatial ecosystem and that MapML can be easily integrated into implementations of OGC API Standards.  

The Data Quality and AI track of the code sprint sought to implement support for the Training Data Markup Language for Artificial Intelligence (TrainingDML-AI) Standard and for a Data Quality Measures Register based on the ISO 19157 series of Standards. The TrainingDML-AI Standard offers a conceptual model and data encodings for geospatial machine learning training data. The engineering report concludes that the use cases for machine readable and executable provenance chains should be widened to include specific Machine Learning (ML) training data use cases. The ability to sample, correct, and train large datasets should have a reproducible method for training models.

The Validators track of the code sprint sought to extend and implement various tools for testing datasets and products for compliance to OGC Standards. In a previous code sprint a https://geonovum-labs.github.io/json-fg-linter/[JSON-FG Linter] was developed. A linter checks the correctness of code or encoding format inside an Editor application while a user is writing or editing. In this code sprint, some of the participants sought to expand on the previous work by creating a linter for OGC API - Features. Another team of participants sought to implement an Executable Test Suite (ETS) for TrainingDML-AI. The engineering report concludes that there is significant potential for client-side validators such as the Linter to enhance the developer experience, alongside server-side validators such as TEAM Engine.

The code sprint was held as a generic code sprint meaning that all OGC working groups were encouraged to participate in the event. As a result, several OGC Standards Working Groups (SWGs) set up teams of developers to collaborate with during the three-day event. In addition to providing software developers with an environment for collaborative coding and experimentation, the code sprint also provided opportunities for thought leadership through presentations and tutorials in the Mentor Stream. This made the code sprint a rich environment for knowledge transfer across teams, as well as for nurturing cross-functional teams.

The sprint participants made the following recommendations regarding potential experiments in future Collaborative Solutions and Innovation (COSI) Program initiatives:

* OGC API - 3D Geovolumes experimentation in the context of Digital Twins
* CDB2 experimentation in the context of Digital Twins
* Experimentation on consistency of metadata frameworks
* Experimentation on consistency of parameter and schema fragments in APIs
* Experimentation on OGC API - Features and Geocoding

The sprint participants made the following recommendations regarding prototype development in future COSI initiatives:

* Initiative on Urban Digital Twins
* An activity building on the ISO metadata activity
* Prototyping of an HTML MapML validator, possibly as a service. See https://github.com/Maps4HTML/validator-mapml for ideas.
* Prototyping of extension of MapML to enable it to consume the JSON-based payloads that are described in the OGC API family of standards

The sprint participants made the following recommendations regarding future discussions in working groups and the Standards Program:

* Discussion on consistency of parameter and schema fragments in APIs
* Development of a roadmap for a possible TrainingDML-AI conformance class for OGC API - Records
* Guidance on the consistency of scale between Observations, Measurements, and Samples (OMS) and the API Standards
* Addition of a security element in future versions of TrainingDML-AI and other metadata encodings
* Run a code sprint focused on machine-readable provenance chains, model reproducibility, and recording data quality.
* Update OGC RAINBOW to offer executable code and variable injection to ensure the chains are machine readable.
* Test the process of machine-readable provenance chains with several different datasets with a focus on model reproducibility.
* Provide feedback to ISO/TC 211 on findings regarding Data Quality and AI.


== Submitters

All questions regarding this document should be directed to the editors or the contributors:

[%unnumbered%]
.Submitters
[options="header"]
|===
|	Name | Organization | Role
|	Gobe Hobona| OGC | Editor
|	Joana Simoes | OGC |Editor
|	Tom Kralidis | OSGeo | Contributor
|	Chris Little | Met Office | Contributor
|	Frank Terpstra | Geonovum | Contributor
|	Joost Farla | Geonovum | Contributor
|	Maxime Collombin | University of Applied Sciences, Western Switzerland (HEIG-VD)  | Contributor
|	Sam Meek |  Helyx Secure Information Systems | Contributor
|	Peter Rushforth | Natural Resources Canada | Contributor
|	Aliyan Haq | Natural Resources Canada | Contributor
|	Rui Cavaco | Norte Portugal Regional Coordination and Development Commission | Contributor
|	Ivana Ivanova | Curtin University | Contributor
|	Jerome St-Louis | Ecere | Contributor
|	Ricardo Garcia Silva | Geobeyond | Contributor
|	Samantha Lavender | Pixalytics Ltd | Contributor
|	Joan Maso | UAB-CREAF | Contributor
|	Panagiotis (Peter) A. Vretanos | CubeWerx Inc. | Contributor
|===
