== Lessons learnt

=== Harvesting

* It's important to be clear about what harvesting means.
* Keeping the metadata close to the data is more efficient than copying the metadata to a separate server.
* Ideally harvesting would be of selected bits of metadata instead of the complete metadata record.
* There are different types of harvesting, in some cases there may be some processing needed. One type of approach means harvesting the discovery metadata.
* In some cases, augmented metadata may need to be pushed back to the source.
* We need to be clear about what we mean when we say "close to the data".

=== Harmonisation between STAC and OGC API Records

* Modified the create and updated times to match the way STAC does it.  That is
  these are the created and updated times that are associated with the record.
* The created and updated time associated with the resource that the record
  describes are now part of the `link` structure to match what STAC does with
  asserts.  The idea is that a record describes a resource(s).  That record then
  points to one or more accessible representations of the resource(s).  For
  example, the record describes a dataset and that dataset can be accessed via
  an API or downloaded as a geopackage or downloaded as a zipped SHAPE file.
* Each of these representations may have different create and updated times so
  it makes sence to move that information into the link (or the asset in the 
  case of STAC).

=== The consideration of adding JSON-FG as another encoding for OGC API Records

* There is not an identified need for JSON-FG encodings in OGC API Records and STAC. However, it could be identified in the future.
* The canonical time is a top-level element in JSON-FG. This could be useful for OGC API Records.
* More feedback is needed

=== ISO metadata and OGC API Records

* Expressing ISO 19115 metadata in OGC API Records should focus on discovery elements.
* Initial prototyping has been focused on Keywords to Themes
* What is needed is a profile that enables us to work with ISO 19115
* Content negotiation by profile could be useful. 
* The incremental approach would be useful. 
* It may be necessary to also design a JSON profile of ISO 19139 as well.
* There are various considerations relating to alignment with ISO 19115 e.g. alignment with DCAT
* We need to balance how deeply we want to represent ISO metadata in JSON

=== Versioning

* Versioning means that an API maintains the versions of a record over time.
* By default, GET'ing a record gets the latest version but previous versions
  should be accessible too.
* There is a stale STAC extension that looks like it provides a good start
  here https://github.com/stac-extensions/version.
** @m-mohr said we are free to use and modify as we see fit
* Other considerations need to be taken into account too related to
  transactions since each update will add a new version of a record and a
  delete with deprecate a record but no remove it from the system.
* More feedback will be needed.  Also, this is something that should be 
  undertaken by the OGC API Feature SWG since they provide the API for records.

== Future Work

=== Innovation work

* Initiatives to facilitate implementation of JSON-FG (e.g. 3D, cadastral data, etc)
* Initiatives to facilitate implementation of catalogues
* Prototyping of tools for creating metadata (e.g. the automated STAC metadata crawler demonstrated during the sprint)
* 

=== Standards

* Outreach for JSON-FG
* Code Sprint for designing profiles of JSON-FG for different communities of interest
* Documentation of the different roles of catalogues and API, as well as guidance on when to use them
* Code Sprint on versioning, possibly combining an OGC API Features Part 4 with OGC API Records
* Exploring how to move GeoDCAT forward within OGC




