= Immediate Lessons and Next Steps

== Immediate Lessons

* There is concern about the format for presenting attribution of collections and collection metadata. There is a need for some compromise on the attribution format.
* The code sprints provide an opportunity for feedback from more developers within and outside of the OGC and OSGeo community.
* There is a need to always have a bbox response in the HTTP header, to help with determing the extent of the data returned.
* OGC API standards offer an improved developer experience compared to the OGC Web Services suite of standards. 
* The examples in OGC API standards are absolutely key to helping developers to implement the standards.
* There is a frequently asked question of: What is the relationship between OGC API Records and STAC? There is a need for clear communications on what the relationship is and which standard to use where. There is a need to delineate these from both a communications and technical.
* There is a need to make OGC API standards stand out.
* There is some similarity between STAC and some of the OGC API Standards. STAC also uses OGC API Features. The idea is to specify OGC API Records such that STAC can be a profile of OGC API Records.
* Which some resources it is not sufficient to record a link to a resource. For example, with a WMS there would be a need to parse the capabilities.

== Next Steps for the innovation side

* Prototypes of crawlable catalogues. Currently there are several searchable catalogues but not crawlable ones.
* More spec validation work for OGC API Records.
* More experiments for OGC API Processes - Workflows extension. This could try out the various workflow approaches. https://github.com/opengeospatial/ideas/issues/115
* Experimentation on how a processing server can interact properly with other OGC API implementations that serve data. For example, in this code sprint there was an implementation of OGC API Processes (ZOO Project) that interacted with an OGC API Features implementation (MapServer).
* Experimentation with OGC's geoparquet specification and Apache Arrow.

== Next Steps for the standards side

* To improve examples and documentation related to OGC API Records.
* To advance the development of the Executable Test Suites of OGC API Processes, Tiles and Coverages.
