
////
Preface sections must include [.preface] attribute
in order to get them placed in the preface area (and not in the main content).

Keywords specified in document preamble will display in this area
after the abstract
////

[.preface]
== Abstract

The subject of this Engineering Report (ER) is a code sprint that was held from October 30th to November 1st, 2023 to advance the support and development of open standards within the developer community. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Ordnance Survey (OS), the European Union Satellite Centre (SatCen), US National Geospatial Intelligence Agency (NGA), and the UK Defence Science and Technology Laboratory (Dstl). 


[.preface]
== Executive Summary

Advances in computing, storage, sensing and other technology areas continue to find a place in the geospatial ecosystem that makes location information findable, accessible, interoperable and reusable. To enable geospatial standards to meet the likely interoperability needs of future technologies, it is necessary for Standards Development Organizations (SDOs) such as the OGC to continue to innovate. Such innovation relies on the ability to develop new standards and improve existing ones to better address emerging interoperability challenges. Code sprints are one of a number of initiative types that the OGC conducts to accelerate such innovation. A code sprint is a collaborative and inclusive event driven by innovative and rapid programming with minimal process and organization constraints to support the development of new applications and candidate standards.

The focus of this Engineering Report (ER) is a code sprint that was held from October 30th to November 1st, 2023. The code sprint was organized by the Open Geospatial Consortium (OGC) and hosted by Geovation in London, England. The code sprint was sponsored by Ordnance Survey (OS) at the Gold-level, as well as the European Union Satellite Centre (SatCen), US National Geospatial Intelligence Agency (NGA), and the UK Defence Science and Technology Laboratory (Dstl) at the Silver-level. As with previous OGC Code Sprints, a key goal of the October 2023 Open Standards Code Sprint was the acceleration of the development of OGC Standards and their implementation in software products. 

Standards in focus for this code sprint included several OGC API, data model, and encoding standards. In addition to OGC Standards, the code sprint also included a thread focusing on the "GEOINT Imagery Media for ISR" (GIMI) profile of the ISO Base Media File Format (ISOBMFF) and the High Efficiency Image Format (HEIF). The engineering report concludes that the code sprint met all of its objectives and achieved its goal of accelerating the development of OGC Standards and their implementation in software products. 

In relation to emerging extensions to OGC API Standards, the engineering report concludes that the Publish/Subscribe (PubSub), Security, and Schemas capabilities examined in this code sprint could potentially support other OGC API Standards. Regarding GIMI, the engineering report concludes that with minor changes to popular open-source base libraries a wide range of software can quickly make use of GIMI capabilities.

Regarding the Model for Underground Data Definition and Integration (MUDDI), the engineering report concludes that the MUDDI Conceptual Model is implementable, and could easily be used as the basis for a logical model that can be encoded in a variety of formats. As for JSON-FG, the engineering report concludes that due to the evident increase in adoption across the developer community, there is an increasing need to offer validators so that developers can check for compliance more easily. 

The sprint participants made the following recommendations for future work items on OGC API Standards:

* Extension of OGC API - Records to support faceting and federated search.
* Use case experimentation to examine how the Publish/Subscribe approach can support various OGC API standards workflows
* Prototyping and specification on an OpenAPI definition document for the OGC SensorThings API Standard
* Additional support for multiband raster data in OGC API - Maps/Tiles/Coverages (e.g. multispectral imagery, etc). 

The sprint participants made the following recommendations for future work items on OGC Encoding Standards:

* Tiled complex, signed, and floating-point data in multiband raster data. 
* Performance benchmarking between various imagery formats, for a variety of use cases.
* Extraction of the conceptual model of GMLJP2 to make it applicable to any ISOBMFF profile.
* Development of an Implementation Standard for the logical model and encoding of data that conforms to the MUDDI.
* Use of the MUDDI logical schema as a template for MUDDI compliance. 

The sprint participants made the following recommendations for future work items on GIMI:

* Extension of open-source base libraries used by several other products for creation and modification of GIMI files
* Prototype streaming of large images from client applications to servers for storage through OGC API - Processes
* Prototyping of a JavaScript Object Notation (JSON) encoded alternative to Key-Length-Value (KLV) metadata for use in GIMI files




== Submitters

All questions regarding this document should be directed to the editor or the contributors:

[%unnumbered%]
.Submitters
[options="header"]
|===
|	Name | Organization | Role
|	Gobe Hobona| OGC | Editor
|	Joana Simoes | OGC |Editor
|	Tom Kralidis | Meteorological Service of Canada |Editor
|	Andreas Matheus	|	Secure Dimensions	|	Contributor
|	Iván Sánchez Ortega	| OSGeo	|	Contributor
|	Florent Gravin	|	Camptocamp	|	Contributor
|	Clemens Portele	|	interactive instruments GmbH	|	Contributor
|	Johannes Echterhoff	|	interactive instruments GmbH	|	Contributor
|	Jérôme Jacovella-St-Louis	| Ecere Corporation	|	Contributor
|	Brad Hards	| 	|	Contributor
|	Sine Kelly	|	Esri UK Ltd	|	Contributor
|	Rebecca Aspin	|	Ordnance Survey	|	Contributor
|	Miles Austen	|	Ordnance Survey	|	Contributor
|	Nikita Dabizha	|	VOLTQUANT	|	Contributor
|	George Kolokotronis	|	VOLTQUANT	|	Contributor
|	Mete Ercan Pakdil	|	Mott MacDonald	|	Contributor
|	Núria Julià Selvas	|	CREAF	|	Contributor
|	Satish Sankaran	|	Esri	|	Contributor
|	Jonathan Bates	|	GeoPlace LLP	|	Contributor
|	Conor Lambert	|	Ordnance Survey	|	Contributor
|	Ricardo Silva	|	Geobeyond	|	Contributor
|	Arnoud de Boer	|	Geonovum	|	Contributor
|	Goncalo Lopes	|	NeuroGEARS Ltd	|	Contributor
|	Joe Guyatt	|	Ordnance Survey	|	Contributor
|	Devon Sookhoo	|	Trax	|	Contributor
|	Rob Smith	|	Away Team Software	|	Contributor
|	James Clarke	|	Ordnance Survey	|	Contributor
|	Richard Hargreaves	|	Ordnance Survey	|	Contributor
|	Neil Kirk	|	Envitia Ltd	|	Contributor
|	Alex Scott-Johns	|	Envitia Ltd	|	Contributor
|	Dave Rowe	|	Ordnance Survey	|	Contributor
|	Carsten Roensdorf	|	Ordnance Survey	|	Contributor
|	Simon Smith	|	Ordnance Survey	|	Contributor
|	Chris Popplestone	|	Ordnance Survey	|	Contributor
|	Neil Brammall	|	Geospatial Commission	|	Contributor
|	Gareth Boyes	|	MGISS	|	Contributor
|	Michael Gordon	|	Ordnance Survey	|	Contributor
|	Colin Sawkins	|	Cadent Gas Limited	|	Contributor
|	Matthew Lewis	|	Esri UK	|	Contributor
|	Sumit Sen	|	GISE Hub, IIT Bombay	|	Contributor
|	Paul Hann	|	Esri UK	|	Contributor
|	Joost Farla	|	Geonovum	|	Contributor
|	Samantha Lavender	|	Pixalytics Ltd	|	Contributor
|	Panagiotis (Peter) Vretanos	|	MariaDB / CubeWerx	|	Contributor
|	Lucio Colaiacomo	|	EU SatCen	|	Contributor
|	Scott Simmons	|	OGC	|	Contributor
|	Chris Little	|	Met Office	|	Contributor
|	Rahul Sharma	|	Cognizant UK	|	Contributor
|	Michael Leedahl	|	Maxar	|	Contributor
|	Ashiraf Kyabainze	|	AT HAUSE LIMITED	|	Contributor
|	Linda van den Brink	|	Geonovum	|	Contributor
|	Ingo Simonis	|	OGC	|	Contributor
|	Thomas Hodson	|	ECMWF	|	Contributor
|	Joan Maso	|	UAB-CREAF	|	Contributor
|	Devon Sookhoo	|	TRAX International Corporation	|	Contributor
|	Joe Stufflebeam	|	TRAX International Corporation	|	Contributor
|	Dean Hintz	|	Safe Software	|	Contributor
|	Ryan Franz	|	FlightSafety International	|	Contributor
|	Hylke van der Schaaf	|	Fraunhofer Gesellschaft	|	Contributor

|=== 
