
== Introduction

Advances in computing, storage, sensing and other technology areas continue to find a place in the geospatial ecosystem that makes location information findable, accessible, interoperable and reusable. To enable geospatial standards to meet the likely interoperability needs of future technologies, it is necessary for Standards Development Organizations (SDOs) such as the OGC to continue to innovate. Such innovation relies on the ability to develop new standards and improve existing ones to better address emerging interoperability challenges. Code sprints are one of a number of initiative types that the OGC conducts to accelerate such innovation.

A code sprint is a collaborative and inclusive event driven by innovative and rapid programming with minimal process and organization constraints to support the development of new applications and candidate standards. The subject of this Engineering Report (ER) is the OGC's October 2023 Open Standards Code Sprint that was held from October 30th to November 1st in London, England. The ER presents the high-level architecture of the code sprint and describes each of the standards and software packages that were deployed in support of the code sprint. The ER also discusses the results and presents a set of conclusions and recommendations.
