
== Introduction

Code sprints are one of a number of initiative types that the OGC holds during the course of each year. Other types of initiatives are design experiments, pilots, plugfests, operational exercises, interoperability experiments, and testbeds. OGC Code sprints can be either 'universal' or 'focused'. All OGC working groups are invited and encouraged to set up a thread in a universal code sprint, whereas a focused code sprint is tailored to limit the number of standards in-focus to approximately three.

The October 2023 Open Standards Code Sprint was held as a universal code sprint. This means that all OGC working groups were encouraged to participate. As a result, several OGC Standards Working Groups (SWGs) set up teams of developers to collaborate during the three-day event. Whilst individual developers work on specific standards during the code sprint, they also get the opportunity to interact and discuss with other developers working on other standards. This makes code sprints a rich environment for knowledge transfer across teams, as well as for nurturing cross-functional teams.

This ER presents the high-level architecture of the code sprint and describes each of the standards and software packages that were deployed in support of the code sprint. The ER also discusses the results and presents a set of conclusions and recommendations. The recommendations identify ideas for future work, some of which may be more appropriate for testbeds, pilots, or other types of OGC initiatives. Therefore, the reader is encouraged to consider the recommended future work within the context of all OGC Standards development, collaborative solutions, and innovation activities.
