[[discussion_mapml]]
==== MapML

Experimentation with support for MapML proved successful in that multiple applications were extended to enable support for MapML as documented in <<results_mapml>>. Some of the participants commented that the implementation of a simple client web application is where MapML really shines, as it makes it simple for consumers of geospatial data to setup an HTML document with a map and relevant data. The participants also noted that the interactive nature of the MapML viewer gives the user the freedom to reposition a map by panning and zooming. This is a useful capability if the initial loading of map places the map in a location that is different from the location required by a user. 

However, the participants also noted that with regard to the work done in order to support MapML on the backend, there seems to be some duplication of effort, which clashes with some of the capabilities found in the OGC API Standards. The adoption of a custom MapML document type, based on XHTML, while appropriate for the frontend, leads to the server having to perform additional serialization of basically the same payloads which are being generated as JSON. This can be seen both in the case of serving MapML tile metadata and also when serving MapML features. This suggests a need to enable future versions of MapML to support JSON-encoded data served by implementations of OGC API Standards.

To make MapML more appealing to developers of server-side software, there should be consideration of how to enable MapML to consume the JSON-based payloads that are described in the OGC API family of standards. This could be an area for future development in a code sprint or other OGC initiative. Since OGC API - Tiles is an approved OGC Standard, formalizing support for OGC API - Tiles within MapML viewers could be a high priority target. Others that could be considered in the long run are OGC API - DGGS and OGC API - GeoDataCubes. All three specifications are concerned with partitioning space and thus could be good candidate direct support in MapML. Support for OGC API - Maps was demonstrated in this code sprint, however this should be expanded in future code sprints with a wider range of applications.

Moving forward, the ease of integrating the MapML viewer into various applications during the code sprint raises the question of how best MapML could be brought into the OGC's Standards Baseline. Some of the routes that are available to the MapML community include the OGC Community Standard route or the OGC Standard route. It is also noted that OGC and the World Wide Web Consortium (W3C) have a long standing relationship that has produced multiple standards. Both organizations have been supportive of the development of MapML. The requirements and conditions of the different routes to standardization are out of scope of this engineering report, however they are highlighted here for further discussion within the relevant communities.

