[[discussion_mapml]]
==== MapML

Experimentation with support for MapML proved successful in that multiple applications were extended to enable support for MapML as documented in <<results_mapml>>. Some of the participants commented that the implementation of a simple client web application is where MapML really shines, as it makes it simple for consumers of geospatial data to setup an HTML document with a map and relevant data. The participants also noted that the interactive nature of the MapML viewer gives the user the freedom to reposition a map by panning and zooming. This is a useful capability if the initial loading of map places the map in a location that is different from the location required by a user. 

However, the participants also noted that with regard to the work done in order to support MapML on the backend, there seems to be some duplication of effort, which clashes with the perscriptions found in the OGC API Standards. The adoption of a custom MapML document type, based on XHTML, while appropriate for the frontend, leads to the server having to perform additional serialization of basically the same payloads which are being generated as JSON. This can be seen both in the case of serving MapML tile metadata and also when serving MapML features. This suggests a need to enable future versions of MapML to support JSON-encoded data served by implementations of OGC API Standards, as outlined in <<future_work_mapml>>.