[[discussion_sta_cs]]
==== Relationship between OGC SensorThings API and OGC API - Connected Systems

The code sprint hosted a discussion on the relationship between the OGC SensorThings API Standard and the OGC API - Connected Systems candidate Standard.  The purpose of the discussion was to determine the commonalities and differences between the OGC SensorThings API Standard and OGC API – Connected Systems candidate Standard so that a consistent message can be presented to the market. Early in the session, it was observed that collaboration between the SWGs could be improved. It is envisaged therefore that the discussion summarized in this section will help to improve collaboration between the SWGs and consistency in messaging.

The first activity during the session was to review the table of design choices which is presented in https://docs.ogc.org/DRAFTS/23-001r0.html#_ogc_sensorthings_api_standard[Annex B.9] of OGC API - Connected Systems - Part 1: Feature Resources. The table presents a comparison of the design choices made in the development of the two standards. The participants noted that the OGC SensorThings API specifies support for ‘any’ type of observation and thus does not identify a set list of supported observation types. In contrast, OGC API – Connected Systems lists the observation types that the standard supports namely scalar, vector, N-D coverage, and video.

.Comparison of design choices made in OGC API - Connected Systems and OGC SensorThings API (reproduced from a draft version of OGC 23-001 on 19 July 2024)
[width="100%",cols="3,5,5",options="header"]
|====
| *Design Choice*                 | *Connected Systems*                                        | *SensorThings*
| API Platform                    | Extension of OGC API Common and OGC - API Features.        | OData Version 4.0
| Query Language                  | Query string arguments, decoupled from resource encoding.  | Generic query language inherited from OData.
| Resource Model                  | Based on SOSA/SSN/OMS and SensorML.                        | Simplified and adapted from O&M.
| Supported Observation Types     | Scalar, vector, N-D coverage, video.                       | Scalar and simple records only.
| Multiple Format Support         | Yes, including non-JSON such as https://protobuf.dev/[Protocol Buffers]
                                    or other binary formats.                                   | OData compatible JSON only.
|====

The participants noted that rather than focus on how the standards implement certain capabilities, the discussion should instead focus on the use cases that addressed by the standards. There was agreement that use cases would be more appropriate for helping to establish a consistent message to the market. It was noted that several technical and domain use cases are documented in the Reviewers Guide of OGC API – Connected Systems. At the time of the code sprint, the reviewers’ guide offered 25 use cases.

There was an observation made that the ability to identify, describe in detail and integrate different sensor systems is one of the motivations for OGC API – Connected Systems and thus a key differentiator from OGC SensorThings API. That is, as the name suggests, OGC API - Connected Systems is designed to support the deployment and connection of various systems, some of which are likely to include sensors. The domain use cases presented in the Reviewers' Guide include use cases that highlight this ability to connect different systems.

The key differentiators can therefore be summarized as follows:

* The level of complexity of the system(s) and what you need to describe them
* How you can query that complexity
* Connectivity between the systems

Taking the example of a satellite, the participants explained that an application that required knowledge of where a satellite was, how the satellite was operated, and the resulting observational data would require the capabilities offered by OGC API - Connected Systems. In contrast, an application that only required the resulting observational data and not details of the system collecting the data could be sufficiently supported by an implementation of the OGC SensorThings API.
